"""
Test cases for cancel_invoice RPC: non-existent payment_hash, cancel in Open/Cancelled/Expired/
Received/Paid states, and send_payment after cancel.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    HashAlgorithm,
    InvoiceStatus,
    PaymentStatus,
    Timeout,
)


class TestCancelInvoice(FiberTest):
    """
    Test cancel_invoice RPC: non-existent payment_hash; cancel in Open, Cancelled, Expired,
    Received, Paid states; assert get_invoice status Cancelled and payment behavior after cancel.
    """

    # FiberTest.debug = True

    def test_not_exist_payment_hash(self):
        """
        Test case for canceling an invoice with a non-existent payment hash.

        Steps:
        1. Generate a random preimage to simulate a non-existent payment hash.
        2. Attempt to cancel the invoice with the generated payment hash.
        3. Verify that the expected error message "invoice not found" is raised.

        Returns:
            None
        """
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().cancel_invoice(
                {"payment_hash": self.generate_random_preimage()}
            )
        expected_error_message = "invoice not found"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_cancel_invoice_that_statue_is_open(self):
        """
        Cancel an invoice in Open state; verify status becomes Cancelled.
        Step 1: Create a new invoice.
        Step 2: Cancel the created invoice.
        Step 3: Query the invoice to verify its status is Cancelled.
        """
        # Step 1: Create a new invoice
        preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 2: Cancel the created invoice
        self.fiber1.get_client().cancel_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )

        # Step 3: Query the invoice to verify its status is Cancelled
        self.assert_invoice_status(
            self.fiber1, invoice["invoice"]["data"]["payment_hash"], InvoiceStatus.CANCELLED
        )

    def test_cancel_invoice_that_statue_is_cancelled(self):
        """
        Test case for canceling an invoice that is already in the 'Cancelled' state.

        Steps:
        1. Create a new invoice.
        2. Cancel the created invoice.
        3. Attempt to cancel the invoice again.
        4. Verify that the expected error message "invoice can not be canceled, current status: Cancelled" is raised.

        Returns:
            None
        """
        # Step 1: Generate a random preimage and create a new invoice
        preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 2: Cancel the created invoice
        self.fiber1.get_client().cancel_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )

        # Step 3: Query the invoice to verify its status is Cancelled
        self.assert_invoice_status(
            self.fiber1, invoice["invoice"]["data"]["payment_hash"], InvoiceStatus.CANCELLED
        )

        # Step 4: Attempt to cancel the invoice again and verify the expected error message
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().cancel_invoice(
                {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
            )
        expected_error_message = (
            "invoice can not be canceled, current status: Cancelled"
        )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_cancel_invoice_that_statue_is_expired(self):
        """
        Test case for canceling an invoice that is in the 'Expired' state.

        Steps:
        1. Generate a random preimage and create a new invoice with an expiry of 0.
        2. Query the invoice to verify its status is 'Expired'.
        3. Cancel the expired invoice.
        4. Query the invoice again to verify its status is 'Cancelled'.

        Returns:
            None
        """
        # Step 1: Generate a random preimage and create a new invoice with an expiry of 0
        preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0x0",
                "final_cltv": "0x28",
                "payment_preimage": preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 2: Query the invoice to verify its status is Expired
        self.assert_invoice_status(
            self.fiber1, invoice["invoice"]["data"]["payment_hash"], InvoiceStatus.EXPIRED
        )

        # Step 3: Cancel the expired invoice
        result = self.fiber1.get_client().cancel_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )
        assert result["status"] == InvoiceStatus.CANCELLED

        # Step 4: Query the invoice again to verify its status is Cancelled
        self.assert_invoice_status(
            self.fiber1, invoice["invoice"]["data"]["payment_hash"], InvoiceStatus.CANCELLED
        )

    def test_send_failed_that_invoice_cancel(self):
        """
        Test case for sending a payment after an invoice is canceled and ensuring subsequent transactions are not affected.

        Steps:
        1. Open a new channel.
        2. Create a new invoice.
        3. Cancel the created invoice.
        4. Attempt to send a payment using the canceled invoice and verify it fails.
        5. Create a new invoice.
        6. Send a payment using the new invoice and verify it succeeds.
        7. Verify the channel balance is updated correctly.

        Returns:
            None
        """
        # Step 1: Open a new channel
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create a new invoice
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(1)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 3: Cancel the created invoice
        self.fiber1.get_client().cancel_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )

        # Step 4: Attempt to send a payment using the canceled invoice and verify it fails
        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"], PaymentStatus.FAILED
        )

        # Step 5: Create a new invoice
        payment_preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 6: Send a payment using the new invoice and verify it succeeds
        before_channel = self.fiber2.get_client().list_channels({})
        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"], PaymentStatus.SUCCESS
        )
        after_channel = self.fiber2.get_client().list_channels({})

        # Step 7: Verify the channel balance is updated correctly
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

    def test_cancel_invoice_that_statue_is_paid(self):
        """
        Test case for canceling an invoice that is in the 'Paid' state.

        Steps:
        1. Open a new channel.
        2. Create a new invoice.
        3. Send a payment using the created invoice.
        4. Attempt to cancel the invoice and verify the expected error message "invoice can not be canceled, current status: Paid" is raised.

        Returns:
            None
        """
        # Step 1: Open a new channel
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create a new invoice
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(1)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 3: Send a payment using the created invoice
        before_channel = self.fiber2.get_client().list_channels({})
        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"], PaymentStatus.SUCCESS
        )
        after_channel = self.fiber2.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        # Step 4: Attempt to cancel the invoice and verify the expected error message
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().cancel_invoice(
                {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
            )
        expected_error_message = "invoice can not be canceled, current status: Paid"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_cancel_invoice_that_statue_is_receive(self):
        """
        Test case for canceling an invoice that is in the 'Received' state.

        Steps:
        1. Open a new channel.
        2. Create a new invoice.
        3. Send a payment using the created invoice.
        4. Cancel the invoice and verify the payment fails.
        5. Verify the channel balance is unchanged.
        6. Create a new invoice.
        7. Send a payment using the new invoice and verify it succeeds.
        8. Verify the channel balance is updated correctly.

        Returns:
            None
        """
        # Step 1: Open a new channel
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create a new invoice
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(1)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 3: Send a payment using the created invoice
        before_channel = self.fiber2.get_client().list_channels({})
        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )

        # Step 4: Cancel the invoice and verify the payment fails
        self.fiber1.get_client().cancel_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"], PaymentStatus.FAILED
        )

        # Step 5: Verify the channel balance is unchanged
        channels = self.fiber2.get_client().list_channels({})
        assert (
            channels["channels"][0]["local_balance"]
            == before_channel["channels"][0]["local_balance"]
        )
        assert (
            channels["channels"][0]["latest_commitment_transaction_hash"]
            != before_channel["channels"][0]["latest_commitment_transaction_hash"]
        )

        # Step 6: Create a new invoice
        invoice_balance = Amount.ckb(1)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 7: Send a payment using the new invoice and verify it succeeds
        before_channel = self.fiber2.get_client().list_channels({})
        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"], PaymentStatus.SUCCESS
        )
        after_channel = self.fiber2.get_client().list_channels({})

        # Step 8: Verify the channel balance is updated correctly
        assert after_channel["channels"][0]["local_balance"] == hex(
            int(before_channel["channels"][0]["local_balance"], 16) - invoice_balance
        )

    # @pytest.mark.skip("https://github.com/nervosnetwork/fiber/issues/654")
    def test_batch_cancel(self):
        """
        Test case for batch canceling invoices.

        Steps:
        1. Start new fibers.
        2. Open channels between fibers.
        3. Create new invoices.
        4. Send payments and cancel invoices.
        5. Verify payment statuses.
        6. Verify fiber balance.

        Returns:
            None
        """
        cancel_size = 20
        channel_length = 4
        # cancel_size = 5
        # channel_length = 3
        # Step 1: Start new fibers
        for i in range(channel_length - 2):
            self.start_new_fiber(self.generate_account(10000))

        # Step 2: Open channels between fibers
        for i in range(len(self.fibers)):
            self.open_channel(
                self.fibers[i],
                self.fibers[(i + 1) % len(self.fibers)],
                Amount.ckb(1000),
                Amount.ckb(1000),
            )

        # Step 3: Create new invoices
        new_invoices = []
        for i in range(cancel_size):
            new_invoice = (
                self.fibers[0]
                .get_client()
                .new_invoice(
                    {
                        "amount": hex(Amount.ckb(1)),
                        "currency": Currency.FIBD,
                        "description": "test invoice generated by node2",
                        "expiry": "0xe10",
                        "final_cltv": "0x28",
                        "payment_preimage": self.generate_random_preimage(),
                        "hash_algorithm": HashAlgorithm.SHA256,
                    }
                )
            )
            new_invoices.append(new_invoice)

        # Step 4: Send payments and cancel invoices
        for i in range(cancel_size):
            self.fiber1.get_client().send_payment(
                {
                    "invoice": new_invoices[i]["invoice_address"],
                    "allow_self_payment": True,
                }
            )
            self.fiber1.get_client().cancel_invoice(
                {"payment_hash": new_invoices[i]["invoice"]["data"]["payment_hash"]}
            )

        # Step 5: Verify payment statuses
        payment_status = []
        for i in range(cancel_size):
            payment = self.fiber1.get_client().get_payment(
                {"payment_hash": new_invoices[i]["invoice"]["data"]["payment_hash"]}
            )
            payment_status.append(payment)

        for i in range(cancel_size):
            self.wait_payment_state(
                self.fibers[0],
                new_invoices[i]["invoice"]["data"]["payment_hash"],
                PaymentStatus.FAILED,
            )

        # Step 6: Verify fiber balance (2 * 1000 CKB after opening channels)
        balance = self.get_fiber_balance(self.fibers[0])
        assert balance["ckb"]["local_balance"] == Amount.ckb(2000)
