"""
Test cases for accept_channel funding_amount parameter.
Verifies: CKB/UDT funding amount validation and auto-accept behaviour.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.config import DEFAULT_MIN_DEPOSIT_CKB
from framework.constants import (
    Amount,
    Timeout,
    ChannelState,
    PaymentStatus,
    FeeRate,
    Currency,
    HashAlgorithm,
)


class TestFundingAmount(FiberTest):
    """
    Test accept_channel with various funding_amount values (CKB and UDT).
    Verifies: zero, eq/gt/lt auto-accept, overflow and account balance edge cases.
    """

    def test_ckb_funding_amount_zero(self):
        """
        CKB accept_channel with funding_amount 0x0 should raise; error mentions min amount.
        Step 1: Get node information and min CKB funding amount.
        Step 2: Open temporary channel with funding just below minimum.
        Step 3: Attempt to accept with zero funding amount; expect exception.
        Step 4: Assert error message contains expected min amount.
        """
        # Step 1: Get node information and min CKB funding amount
        node_info = self.fiber1.get_client().node_info()
        open_channel_auto_accept_min_ckb_funding_amount = node_info[
            "open_channel_auto_accept_min_ckb_funding_amount"
        ]

        # Step 2: Open temporary channel with funding just below minimum
        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(
                    int(open_channel_auto_accept_min_ckb_funding_amount, 16) - 1
                ),
                "public": True,
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)

        # Step 3: Attempt accept with zero funding amount; expect exception
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().accept_channel(
                {
                    "temporary_channel_id": temporary_channel["temporary_channel_id"],
                    "funding_amount": "0x0",
                }
            )

        # Step 4: Assert error message contains expected min amount (keyword check)
        err = exc_info.value.args[0] if exc_info.value.args else ""
        assert "greater than or equal to" in err or "min" in err.lower(), (
            f"Expected min amount error, actual: {err}"
        )

    def test_udt_funding_amount_zero(self):
        """
        UDT accept_channel with funding_amount 0x0 should succeed; payment and shutdown.
        Step 1: fiber1 open UDT channel; fiber2 accept with 0x0.
        Step 2: Wait channel ready; fiber1 send 1 UDT to fiber2.
        Step 3: Shutdown channel; verify UDT balances (fiber1 4, fiber2 1).
        """
        # Step 1: fiber1 open UDT channel; fiber2 accept with 0x0
        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.udt(5)),
                "public": True,
                "funding_udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        self.fiber2.get_client().accept_channel(
            {
                "temporary_channel_id": temporary_channel["temporary_channel_id"],
                "funding_amount": "0x0",
            }
        )
        # Step 2: Wait channel ready; fiber1 send 1 UDT to fiber2
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.udt(1)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
                "udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1,
            payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()
        # Step 3: Shutdown channel; verify UDT balances (fiber1 4, fiber2 1)
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": hex(FeeRate.DEFAULT),
            }
        )
        tx_hash = self.wait_and_check_tx_pool_fee(
            FeeRate.DEFAULT, False, Timeout.MEDIUM
        )
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        after_account1 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        after_account2 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )

        assert after_account1[-1]["balance"] == Amount.udt(4)
        assert after_account2[-1]["balance"] == Amount.udt(1)

    def test_ckb_funding_amount_eq_auto_accept_channel_ckb_funding_amount(self):
        """
        CKB accept_channel with funding_amount == auto_accept_channel_ckb_funding_amount should succeed.
        Step 1: Get node info and open channel with funding below auto-accept min.
        Step 2: fiber2 accept with funding_amount == auto_accept_channel_ckb_funding_amount.
        Step 3: Wait channel ready; fiber1 send 0.1 CKB to fiber2.
        Step 4: Shutdown channel; verify fiber2 balance increased by 99 CKB.
        """
        # Step 1: Get node info and open channel with funding below auto-accept min
        node_info = self.fiber1.get_client().node_info()
        open_channel_auto_accept_min_ckb_funding_amount = node_info[
            "open_channel_auto_accept_min_ckb_funding_amount"
        ]

        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(
                    int(open_channel_auto_accept_min_ckb_funding_amount, 16) - 1
                ),
                "public": True,
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        # Step 2: fiber2 accept with funding_amount == auto_accept_channel_ckb_funding_amount
        accept_channel_funding_amount = int(
            node_info["auto_accept_channel_ckb_funding_amount"], 16
        )
        self.fiber2.get_client().accept_channel(
            {
                "temporary_channel_id": temporary_channel["temporary_channel_id"],
                "funding_amount": hex(accept_channel_funding_amount),
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        channels = self.fiber2.get_client().list_channels({})
        assert accept_channel_funding_amount - DEFAULT_MIN_DEPOSIT_CKB == int(
            channels["channels"][0]["local_balance"], 16
        )
        # Step 3: fiber1 send 0.1 CKB to fiber2
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(0.1)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1,
            payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        # Step 4: Shutdown channel; verify fiber2 balance increased by 99 CKB
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": hex(FeeRate.DEFAULT),
            }
        )

        tx_hash = self.wait_and_check_tx_pool_fee(
            FeeRate.DEFAULT, False, Timeout.MEDIUM
        )
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.fiber2.get_account()["address"]["testnet"]
        )
        assert int(after_balance2 - before_balance2) == 99

    def test_ckb_funding_amount_gt_auto_accept_channel_ckb_funding_amount(self):
        """
        CKB accept_channel with funding_amount > auto_accept_channel_ckb_funding_amount should succeed.
        Step 1: Get node info and open channel with funding below auto-accept min.
        Step 2: fiber2 accept with funding_amount > auto_accept_channel_ckb_funding_amount.
        Step 3: Wait channel ready; fiber1 send 0.1 CKB to fiber2.
        Step 4: Shutdown channel; verify fiber2 balance increased by 100 CKB: deposit ckb.
        """
        # Step 1: Get node info and open channel with funding below auto-accept min
        node_info = self.fiber1.get_client().node_info()
        open_channel_auto_accept_min_ckb_funding_amount = node_info[
            "open_channel_auto_accept_min_ckb_funding_amount"
        ]

        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(
                    int(open_channel_auto_accept_min_ckb_funding_amount, 16) - 1
                ),
                "public": True
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        # Step 2: fiber2 accept with funding_amount > auto_accept_channel_ckb_funding_amount
        accept_channel_funding_amount = int(
            node_info["auto_accept_channel_ckb_funding_amount"], 16
        ) + Amount.ckb(1)
        self.fiber2.get_client().accept_channel(
            {
                "temporary_channel_id": temporary_channel["temporary_channel_id"],
                "funding_amount": hex(accept_channel_funding_amount),
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        channels = self.fiber2.get_client().list_channels({})
        assert accept_channel_funding_amount - DEFAULT_MIN_DEPOSIT_CKB == int(
            channels["channels"][0]["local_balance"], 16
        )
        # Step 3: fiber1 send 0.1 CKB to fiber2
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(0.1)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1,
            payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        # Step 4: Shutdown channel; verify fiber2 balance increased by 100 CKB
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": hex(FeeRate.DEFAULT),
            }
        )
        shutdown_tx = self.wait_and_check_tx_pool_fee(
            FeeRate.DEFAULT, False, Timeout.MEDIUM
        )
        self.Miner.miner_until_tx_committed(self.node, shutdown_tx)
        after_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.fiber1.get_account()["address"]["testnet"]
        )
        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.fiber2.get_account()["address"]["testnet"]
        )
        assert int(after_balance2 - before_balance2) == 100

    @pytest.mark.skip("repeat")
    def test_ckb_funding_amount_lt_account(self):
        """
        CKB accept_channel with funding_amount < account balance (placeholder).
        Step 1: TBD.
        """
        # self.test_ckb_funding_amount_eq_auto_accept_channel_ckb_funding_amount()

    @pytest.mark.skip(
        reason="Dev fiber: accept_channel(udt>0) builds tx with cellDep only xudt, causes ScriptNotFound"
    )
    def test_udt_funding_amount_lt_account(self):
        """
        UDT accept_channel with funding_amount < account balance (skipped due to ScriptNotFound).
        Step 1: Faucet both fibers; open UDT channel; fiber2 accept with funding_amount > open amount.
        Step 2: Send payment; shutdown; verify UDT balances.
        """
        # Step 1: Faucet both fibers; open UDT channel; fiber2 accept with funding_amount > open amount
        self.faucet(
            self.fiber2.account_private,
            1000,
            self.fiber1.account_private,
            Amount.udt(100000),
        )
        self.faucet(
            self.fiber1.account_private,
            1000,
            self.fiber1.account_private,
            Amount.udt(100000),
        )

        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(5)),
                "public": True,
                "funding_udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        self.fiber2.get_client().accept_channel(
            {
                "temporary_channel_id": temporary_channel["temporary_channel_id"],
                "funding_amount": hex(Amount.ckb(10000)),
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        # Step 2: fiber1 send 0.1 CKB to fiber2
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(0.1)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
                "udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1,
            payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        # Step 3: fiber2 send 1000 CKB to fiber1
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(1000)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
                "udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        before_channel = self.fiber2.get_client().list_channels({})

        payment = self.fiber2.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1,
            payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel = self.fiber2.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        before_account1 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        before_account2 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )
        # Step 4: Shutdown channel; verify UDT balances
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": hex(FeeRate.DEFAULT),
            }
        )
        tx_hash = self.wait_and_check_tx_pool_fee(
            FeeRate.DEFAULT, False, Timeout.MEDIUM
        )
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        after_account1 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        after_account2 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )

        assert after_account1[-1]["balance"] == Amount.ckb(1003)  # 5 - 1 + 999
        assert after_account2[-1]["balance"] == Amount.ckb(2)  # 10000 + 1 - 9999

    def test_ckb_funding_amount_gt_account(self):
        """
        CKB accept_channel with funding_amount > account balance should fail; retry yields No channel.
        Step 1: fiber1 open channel; fiber2 accept with funding_amount > account capacity.
        Step 2: Assert no channel created.
        Step 3: Retry accept_channel; expect "No channel with temp id" error.
        """
        # Step 1: fiber1 open channel; fiber2 accept with funding_amount > account capacity
        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(100)),
                "public": True,
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        account2_capacity = self.Ckb_cli.wallet_get_capacity(
            self.fiber2.get_account()["address"]["testnet"]
        )
        self.fiber2.get_client().accept_channel(
            {
                "temporary_channel_id": temporary_channel["temporary_channel_id"],
                "funding_amount": hex((int(account2_capacity) + 1) * Amount.CKB),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        # Step 2: Assert no channel created
        channels = self.fiber1.get_client().list_channels({})
        assert len(channels["channels"]) == 0

        # Step 3: Retry accept_channel; expect "No channel with temp id" error
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().accept_channel(
                {
                    "temporary_channel_id": temporary_channel["temporary_channel_id"],
                    "funding_amount": hex(Amount.ckb(1000)),
                }
            )
        err = exc_info.value.args[0] if exc_info.value.args else ""
        assert "No channel with temp id" in err, f"Expected retry error, actual: {err}"

    def test_funding_amount_over_flow(self):
        """
        accept_channel with funding_amount overflow (exceeds u64) should reject with Invalid params.
        Step 1: fiber1 open UDT channel.
        Step 2: fiber2 accept with overflow funding_amount; expect Invalid params error.
        """
        # Step 1: fiber1 open UDT channel
        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(5)),
                "public": True,
                "funding_udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        # Step 2: fiber2 accept with overflow funding_amount; expect Invalid params error
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().accept_channel(
                {
                    "temporary_channel_id": temporary_channel["temporary_channel_id"],
                    "funding_amount": "0xffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff",
                }
            )
        err = exc_info.value.args[0] if exc_info.value.args else ""
        assert "Invalid params" in err, f"Expected Invalid params error, actual: {err}"

    def test_udt_funding_amount_gt_account(self):
        """
        UDT accept_channel with funding_amount > account balance should fail; no channel created.
        Step 1: Faucet fiber2 with UDT; fiber1 open UDT channel.
        Step 2: fiber2 accept with funding_amount > UDT balance; expect failure (no channel).
        """
        # Step 1: Faucet fiber2 with UDT; fiber1 open UDT channel
        self.faucet(
            self.fiber2.account_private,
            1000,
            self.fiber1.account_private,
            Amount.udt(100000),
        )
        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(5)),
                "public": True,
                "funding_udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        # Step 2: fiber2 accept with funding_amount > UDT balance; expect failure (no channel)
        self.fiber2.get_client().accept_channel(
            {
                "temporary_channel_id": temporary_channel["temporary_channel_id"],
                "funding_amount": hex(Amount.udt(100000) + 1),
            }
        )

        channels = self.fiber2.get_client().list_channels({})
        assert len(channels["channels"]) == 0

    @pytest.mark.skip(
        reason="Dev fiber: accept_channel(udt>0) builds tx with cellDep only xudt, causes ScriptNotFound"
    )
    def test_udt_multi_funding_amount_gt_account(self):
        """
        UDT accept_channel with funding_amount > account (multi-cell); skipped due to ScriptNotFound.
        Step 1: Faucet both fibers; fiber1 open UDT channel; fiber2 accept with excess funding.
        Step 2: Wait channel ready; fiber1 send 1000 to fiber2.
        Step 3: Shutdown channel; verify UDT balances.
        """
        # Step 1: Faucet both fibers; fiber1 open UDT channel; fiber2 accept with excess funding
        self.faucet(
            self.fiber2.account_private,
            1000,
            self.fiber1.account_private,
            Amount.udt(100000),
        )
        self.faucet(
            self.fiber2.account_private,
            1000,
            self.fiber1.account_private,
            Amount.udt(100000),
        )
        self.faucet(
            self.fiber1.account_private,
            1000,
            self.fiber1.account_private,
            Amount.udt(100000),
        )
        temporary_channel = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1)),
                "public": True,
                "funding_udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
                "commitment_fee_rate": hex(FeeRate.DEFAULT),
                "funding_fee_rate": hex(FeeRate.DEFAULT),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        self.fiber2.get_client().accept_channel(
            {
                "temporary_channel_id": temporary_channel["temporary_channel_id"],
                "funding_amount": hex(Amount.ckb(200000)),
            }
        )

        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: fiber1 send 1000 to fiber2
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(1000)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
                "udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        before_channel = self.fiber2.get_client().list_channels({})

        payment = self.fiber2.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1,
            payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel = self.fiber2.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        # Step 3: Shutdown channel; verify UDT balances
        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": hex(FeeRate.DEFAULT),
            }
        )
        tx_hash = self.wait_and_check_tx_pool_fee(
            FeeRate.DEFAULT, False, Timeout.MEDIUM
        )
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        after_account1 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        after_account2 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )

        assert after_account1[-1]["balance"] == Amount.ckb(1) + invoice_balance
        assert after_account2[-1]["balance"] == Amount.ckb(200000) - invoice_balance
