import time

import pytest

from framework.basic_fiber_with_cch import FiberCchTest


class TestHtlcDelta(FiberCchTest):
    """ """

    @pytest.mark.skip("https://github.com/nervosnetwork/fiber/issues/1218")
    def test_send_btc(self):
        """
        Returns:

        """
        self.fiber3 = self.start_new_fiber(
            self.generate_account(10000, self.fiber1.account_private, 10000 * 100000000)
        )

        self.faucet(
            self.fiber2.account_private,
            0,
            self.fiber1.account_private,
            10000 * 100000000,
        )

        self.open_channel(
            self.fiber2,
            self.fiber1,
            1000 * 100000000,
            1000 * 100000000,
            udt=self.get_account_udt_script(self.fiber1.account_private),
        )
        self.open_channel(
            self.fiber2,
            self.fiber3,
            1000 * 100000000,
            1000 * 100000000,
            udt=self.get_account_udt_script(self.fiber1.account_private),
        )
        invoice = self.fiber3.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                # "payment_preimage": self.generate_random_preimage(),
                "payment_hash": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
                "udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        btc_response = self.fiber1.get_client().receive_btc(
            {"fiber_pay_req": invoice["invoice_address"]}
        )

        self.LNDs[1].ln_cli_with_cmd_without_json(
            f"payinvoice {btc_response['incoming_invoice']['Lightning']} --force &"
        )
        time.sleep(10)
        # todo 确认链路的 htlc 过期时间是否合理
        tlc = self.get_pending_tlc(self.fiber2, btc_response["payment_hash"])
        print("tlc", tlc)
        assert tlc["Inbound"][0]["expiry_seconds"] < 180 * 10 * 60
