import time

from framework.basic_fiber import FiberTest
from framework.test_fiber import FiberConfigPath


class OtherTx(FiberTest):
    fiber_version = FiberConfigPath.CURRENT_DEV_DEBUG

    def test_other_tx(self):
        """
        1. ckb channel 使用udt channel
            预期失败
        2. udt channel 使用ckb channel
            预期失败
        3. ckb channel 使用ckb channel
            预期成功
        4. udt channel 使用udt channel
            预期成功
        """
        self.faucet(
            self.fiber1.account_private,
            0,
            self.fiber1.account_private,
            10000 * 100000000,
        )
        self.open_channel(
            self.fiber1,
            self.fiber2,
            1000 * 100000000,
            1000 * 100000000,
            udt=self.get_account_udt_script(self.fiber1.account_private),
        )
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000)

        # ckb invoice
        ckb_invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
            }
        )

        # udt invoice

        # self.send_invoice_payment()
        # "udt_type_script"
        udt_invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        channels = self.fiber1.get_client().list_channels({})
        if channels["channels"][0]["funding_udt_type_script"] == None:
            ckb_channel_id = channels["channels"][0]["channel_id"]
            udt_channel_id = channels["channels"][1]["channel_id"]
        else:
            ckb_channel_id = channels["channels"][1]["channel_id"]
            udt_channel_id = channels["channels"][0]["channel_id"]
        # udt channel use ckb

        self.fiber2.get_client().add_tlc(
            {
                "channel_id": udt_channel_id,
                "amount": hex(1),
                "payment_hash": ckb_invoice["invoice"]["data"]["payment_hash"],
                "expiry": hex((int(time.time()) + 10) * 1000),
            }
        )
        self.fiber2.get_client().add_tlc(
            {
                "channel_id": ckb_channel_id,
                "amount": hex(1),
                "payment_hash": udt_invoice["invoice"]["data"]["payment_hash"],
                "expiry": hex((int(time.time()) + 10) * 1000),
            }
        )
        time.sleep(10)

        self.wait_invoice_state(
            self.fiber1, udt_invoice["invoice"]["data"]["payment_hash"], "Open"
        )
        self.wait_invoice_state(
            self.fiber1, ckb_invoice["invoice"]["data"]["payment_hash"], "Open"
        )

        self.fiber2.get_client().add_tlc(
            {
                "channel_id": ckb_channel_id,
                "amount": hex(1),
                "payment_hash": ckb_invoice["invoice"]["data"]["payment_hash"],
                "expiry": hex((int(time.time()) + 10) * 1000),
            }
        )
        self.fiber2.get_client().add_tlc(
            {
                "channel_id": udt_channel_id,
                "amount": hex(1),
                "payment_hash": udt_invoice["invoice"]["data"]["payment_hash"],
                "expiry": hex((int(time.time()) + 10) * 1000),
            }
        )
        self.wait_invoice_state(
            self.fiber1, udt_invoice["invoice"]["data"]["payment_hash"], "Paid"
        )
        self.wait_invoice_state(
            self.fiber1, ckb_invoice["invoice"]["data"]["payment_hash"], "Paid"
        )

    def test_00000222(self):
        # self.fiber1.get_client().list_channels({})
        # {"jsonrpc": "2.0", "id": 42, "result": {"channels": [{"channel_id": "0x1b75b3a0c5bde153ba44bc04389642a4247f55ae86e94b93b6347e2e1da696db", "is_public": true, "channel_outpoint": "0x6b4a4822a22f79d7da1fabd465b297c7ef5f5a9c26c858147d3f554ab87cdfdb00000000", "peer_id": "QmQbUhn398CczTBhRrB4Soth9i9QqvJgwzmES32qKjWRaP", "funding_udt_type_script": {"code_hash": "0x102583443ba6cfe5a3ac268bbb4475fb63eb497dce077f126ad3b148d4f4f8f8", "hash_type": "type", "args": "0x32e555f3ff8e135cece1351a6a2971518392c1e30375c1e006ad0ce8eac07947"}, "state": {"state_name": "CHANNEL_READY"}, "local_balance": "0x19968ceb00", "offered_tlc_balance": "0x0", "remote_balance": "0x174876e800", "received_tlc_balance": "0x0", "pending_tlcs": [{"id": "0x0", "amount": "0x1", "payment_hash": "0xb16f75800014b2e4a7a7443fe42dfeebffa17fdb244028035e60d872ed16d192", "expiry": "0x19bba5e6c88", "forwarding_channel_id": null, "forwarding_tlc_id": null, "status": {"Inbound": "RemoveAckConfirmed"}}], "latest_commitment_transaction_hash": "0x46dfa2a04d54058e4817d32596baac9501a635c439598144c39690938e86a138", "created_at": "0x19bba5e17ad", "enabled": true, "tlc_expiry_delta": "0xdbba00", "tlc_fee_proportional_millionths": "0x3e8", "shutdown_transaction_hash": null}, {"channel_id": "0xb224e03b72a76edd1f7a322a1f558ee95a285f27deb95e5e280883109e04927f", "is_public": true, "channel_outpoint": "0x95d01e6b56e9d20ab7b193179d3a0f8b85b7d4c6f5f70da8f3934cb8b24eb08800000000", "peer_id": "QmQbUhn398CczTBhRrB4Soth9i9QqvJgwzmES32qKjWRaP", "funding_udt_type_script": null, "state": {"state_name": "CHANNEL_READY"}, "local_balance": "0x174876e800", "offered_tlc_balance": "0x0", "remote_balance": "0x174876e800", "received_tlc_balance": "0x0", "pending_tlcs": [{"id": "0x0", "amount": "0x1", "payment_hash": "0x871860947fb0f42bd3b5112b4044ea674446f9ba83a9f3c1782587dd6efaa513", "expiry": "0x19bba5e6c88", "forwarding_channel_id": null, "forwarding_tlc_id": null, "status": {"Inbound": "RemoveAckConfirmed"}}], "latest_commitment_transaction_hash": "0x4716d3d0ac7a31ba2ad5d687628d57587990bb7846b5c93885c79995a1d00c2c", "created_at": "0x19bba5dc1b0", "enabled": true, "tlc_expiry_delta": "0xdbba00", "tlc_fee_proportional_millionths": "0x3e8", "shutdown_transaction_hash": null}]}}
        self.get_fiber_graph_balance()
