from framework.basic_fiber import FiberTest


class TestMppWithHashAlgorithm(FiberTest):

    def test_mpp_with_hash_algorithm(self):
        # Placeholder for test logic
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 0)
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 0)

        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1001 * 10000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
                "allow_mpp": True,
                # "allow_trampoline_routing": True,
            }
        )
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                # "max_fee_amount": hex(100000000),
                # "trampoline_hops": [
                #     {
                #         "pubkey": self.fiber2.get_client().node_info()["pubkey"],
                #         # "fee_rate": hex(100000),
                #     },
                # ]
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], "Success")

        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1001 * 10000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "ckb_hash",
                "allow_mpp": True,
                # "allow_trampoline_routing": True,
            }
        )
        payment = self.fiber2.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                # "max_fee_amount": hex(100000000),
                # "trampoline_hops": [
                #     {
                #         "pubkey": self.fiber2.get_client().node_info()["pubkey"],
                #         # "fee_rate": hex(100000),
                #     },
                # ]
            }
        )
        self.wait_payment_state(self.fiber2, payment["payment_hash"], "Success")
