"""
Test cases for MPP with hash algorithm: sha256 and ckb_hash invoice/payment.
"""
from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    Currency,
    HashAlgorithm,
    PaymentStatus,
    Timeout,
)


class TestMppWithHashAlgorithm(FiberTest):
    """
    Test MPP payment with different hash algorithms: sha256 and ckb_hash;
    open two channels fiber1-fiber2, create invoice with allow_mpp and hash_algorithm,
    send payment and wait Success.
    """

    def test_mpp_with_hash_algorithm(self):
        """
        Pay fiber2 invoice with sha256 then fiber1 invoice with ckb_hash; both MPP and Success.
        Step 1: Open two channels fiber1-fiber2 with semantic amounts.
        Step 2: Create fiber2 invoice (sha256, allow_mpp); send payment from fiber1; wait Success.
        Step 3: Create fiber1 invoice (ckb_hash, allow_mpp); send payment from fiber2; wait Success.
        """
        # Step 1: Open two channels fiber1-fiber2 with semantic amounts
        self.open_channel(
            self.fiber1, self.fiber2,
            fiber1_balance=Amount.ckb(1000),
            fiber2_balance=Amount.ckb(0),
        )
        self.open_channel(
            self.fiber1, self.fiber2,
            fiber1_balance=Amount.ckb(1000),
            fiber2_balance=Amount.ckb(0),
        )

        # Step 2: Create fiber2 invoice (sha256, allow_mpp); send payment from fiber1; wait Success
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(100.1)),  # 1001 * 10^7 = 100.1 CKB
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
                "allow_mpp": True,
            }
        )
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )

        # Step 3: Create fiber1 invoice (ckb_hash, allow_mpp); send payment from fiber2; wait Success
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(100.1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.CKB_HASH,
                "allow_mpp": True,
            }
        )
        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
