import time

from framework.basic_fiber import FiberTest
from test_cases.fiber.devnet.settle_invoice.test_settle_invoice import sha256_hex


class TestMpp(FiberTest):
    def test_mpp_2_cost(self):
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.open_channel(self.fiber2, self.fiber3, 1000 * 100000000, 1000 * 100000000)
        self.open_channel(self.fiber2, self.fiber3, 1000 * 100000000, 1000 * 100000000)

        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000)
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000)
        preimage = self.generate_random_preimage()
        payment_hash = sha256_hex(preimage)

        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1001 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_hash": payment_hash,
                "hash_algorithm": "sha256",
                "allow_mpp": True,
            }
        )
        fiber1_payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        fiber3_payment = self.fiber3.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )

        time.sleep(1)
        print("before--settle-----")
        self.fiber1.get_client().get_payment({"payment_hash": payment_hash})
        payment = self.fiber3.get_client().get_payment(
            {
                "payment_hash": payment_hash,
            }
        )
        assert payment["status"] == "Failed"

        self.fiber2.get_client().settle_invoice(
            {"payment_hash": payment_hash, "payment_preimage": preimage}
        )
        time.sleep(1)
        print("after--settle-----")

        payment = self.fiber1.get_client().get_payment({"payment_hash": payment_hash})
        assert payment["status"] == "Success"
