"""
Test cases for settle_invoice with MPP (Multi-Path Payment).
Verifies that when two nodes pay the same MPP invoice, only one succeeds after settle.
"""
import time

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Currency, HashAlgorithm, PaymentStatus, Timeout
from test_cases.fiber.devnet.settle_invoice.test_settle_invoice import sha256_hex


class TestMpp(FiberTest):
    """
    Test settle_invoice with MPP: fiber1 and fiber3 both pay the same MPP invoice.
    One payment fails, one succeeds. After settle, the successful payment completes.
    """
    debug = True
    def test_mpp_2_cost(self):
        """
        Test MPP invoice with two payers: one succeeds, one fails.
        Step 1: Start fiber3 and open channels fiber1-fiber2-fiber3 (2 channels each).
        Step 2: Create MPP invoice on fiber2 (1001 CKB).
        Step 3: Send payment from fiber1 and fiber3 to the same invoice.
        Step 4: Assert one payment fails (both cannot succeed for full amount).
        Step 5: Settle invoice on fiber2.
        Step 6: Wait for both payments to finish; assert one Success, one Failed.
        """
        # Step 1: Start fiber3 and open channels
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.open_channel(
            self.fiber2, self.fiber3,
            Amount.ckb(1000), Amount.ckb(1000)
        )
        self.open_channel(
            self.fiber2, self.fiber3,
            Amount.ckb(1000), Amount.ckb(1000)
        )
        self.open_channel(
            self.fiber1, self.fiber2,
            Amount.ckb(1000), Amount.ckb(1000)
        )
        self.open_channel(
            self.fiber1, self.fiber2,
            Amount.ckb(1000), Amount.ckb(1000)
        )

        # Step 2: Create MPP invoice on fiber2
        preimage = self.generate_random_preimage()
        payment_hash = sha256_hex(preimage)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1001)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "payment_hash": payment_hash,
                "hash_algorithm": HashAlgorithm.SHA256,
                "allow_mpp": True,
            }
        )

        # Step 3: Send payment from fiber1 and fiber3 to the same invoice
        self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.fiber3.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        time.sleep(5)
        # Step 4: Assert one payment fails (both cannot succeed for full amount)
        payment1 = self.fiber1.get_client().get_payment({"payment_hash": payment_hash})
        payment3 = self.fiber3.get_client().get_payment({"payment_hash": payment_hash})
        assert (
            payment3["status"] == PaymentStatus.FAILED
            or payment1["status"] == PaymentStatus.FAILED
        ), "Expected one payment to fail"

        # Step 5: Settle invoice on fiber2
        self.fiber2.get_client().settle_invoice(
            {"payment_hash": payment_hash, "payment_preimage": preimage}
        )

        # Step 6: Wait for both payments to finish; assert one Success, one Failed
        fiber1_payment = self.wait_payment_finished(
            self.fiber1, payment_hash, timeout=Timeout.CHANNEL_READY
        )
        fiber3_payment = self.wait_payment_finished(
            self.fiber3, payment_hash, timeout=Timeout.CHANNEL_READY
        )
        assert fiber1_payment["status"] != fiber3_payment["status"], (
            "Expected one Success and one Failed"
        )
