"""
Test cases for batch settle_invoice.
Verifies concurrent settlement of multiple hold invoices.
"""
import time

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Currency, HashAlgorithm, InvoiceStatus, Timeout
from test_cases.fiber.devnet.settle_invoice.test_settle_invoice import sha256_hex


class TestBatchSettle(FiberTest):
    """
    Test batch settlement of hold invoices.
    Creates 60 invoices each on fiber1 and fiber3, sends payments, waits for Received,
    then settles all invoices concurrently.
    """

    def test_batch_settle(self):
        """
        Test concurrent settlement of multiple hold invoices.
        Step 1: Start fiber3 and open channels fiber1-fiber2-fiber3.
        Step 2: Create 60 hold invoices on fiber1 and fiber3.
        Step 3: Send payments fiber3->fiber1 and fiber1->fiber3.
        Step 4: Wait for all invoices to reach Received.
        Step 5: Settle all invoices concurrently.
        Step 6: Wait for all invoices to reach Paid.
        Step 7: Assert balance changes match expected (60 CKB each direction).
        """
        # Step 1: Start fiber3 and open channels
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        for _ in range(3):
            self.open_channel(
                self.fiber1, self.fiber2,
                Amount.ckb(1000), Amount.ckb(1000)
            )
            self.open_channel(
                self.fiber2, self.fiber3,
                Amount.ckb(1000), Amount.ckb(1000)
            )

        # Step 2: Create 60 hold invoices on fiber1 and fiber3
        for _ in range(1):
            before_balances = self.get_fibers_balance()
            fiber1_invoice_size = 60
            fiber1_invoices = []
            fiber1_preimages = []
            fiber1_invoice_hashes = []
            for _ in range(fiber1_invoice_size):
                preimage = self.generate_random_preimage()
                invoice_hash = sha256_hex(preimage)
                invoice = self.fiber1.get_client().new_invoice(
                    {
                        "amount": hex(Amount.ckb(1)),
                        "currency": Currency.FIBD,
                        "description": "test invoice generated by node2",
                        "payment_hash": invoice_hash,
                        "hash_algorithm": HashAlgorithm.SHA256,
                        "allow_mpp": False,
                    }
                )
                fiber1_invoices.append(invoice)
                fiber1_preimages.append(preimage)
                fiber1_invoice_hashes.append(invoice_hash)

            fiber3_invoice_size = 60
            fiber3_invoices = []
            fiber3_preimages = []
            fiber3_invoice_hashes = []
            for _ in range(fiber3_invoice_size):
                preimage = self.generate_random_preimage()
                invoice_hash = sha256_hex(preimage)
                invoice = self.fiber3.get_client().new_invoice(
                    {
                        "amount": hex(Amount.ckb(1)),
                        "currency": Currency.FIBD,
                        "description": "test invoice generated by node2",
                        "payment_hash": invoice_hash,
                        "hash_algorithm": HashAlgorithm.SHA256,
                        "allow_mpp": False,
                    }
                )
                fiber3_invoices.append(invoice)
                fiber3_preimages.append(preimage)
                fiber3_invoice_hashes.append(invoice_hash)

            # Step 3: Send payments fiber3->fiber1 and fiber1->fiber3
            for invoice in fiber1_invoices:
                self.fiber3.get_client().send_payment(
                    {"invoice": invoice["invoice_address"]}
                )
            for invoice in fiber3_invoices:
                self.fiber1.get_client().send_payment(
                    {"invoice": invoice["invoice_address"]}
                )

            # Step 4: Wait for all invoices to reach Received
            for invoice in fiber3_invoices:
                self.wait_invoice_state(
                    self.fiber3,
                    invoice["invoice"]["data"]["payment_hash"],
                    InvoiceStatus.RECEIVED,
                    timeout=Timeout.CHANNEL_READY,
                )
            for invoice in fiber1_invoices:
                self.wait_invoice_state(
                    self.fiber1,
                    invoice["invoice"]["data"]["payment_hash"],
                    InvoiceStatus.RECEIVED,
                    timeout=Timeout.CHANNEL_READY,
                )

            # Step 5: Settle all invoices concurrently
            for i in range(len(fiber1_invoices)):
                self.fiber1.get_client().settle_invoice(
                    {
                        "payment_hash": fiber1_invoice_hashes[i],
                        "payment_preimage": fiber1_preimages[i],
                    }
                )
            for i in range(len(fiber3_invoices)):
                self.fiber3.get_client().settle_invoice(
                    {
                        "payment_hash": fiber3_invoice_hashes[i],
                        "payment_preimage": fiber3_preimages[i],
                    }
                )

            # Step 6: Wait for all invoices to reach Paid
            for invoice in fiber1_invoices:
                self.wait_invoice_state(
                    self.fiber1,
                    invoice["invoice"]["data"]["payment_hash"],
                    InvoiceStatus.PAID,
                    timeout=Timeout.CHANNEL_READY,
                )
            for invoice in fiber3_invoices:
                self.wait_invoice_state(
                    self.fiber3,
                    invoice["invoice"]["data"]["payment_hash"],
                    InvoiceStatus.PAID,
                    timeout=Timeout.CHANNEL_READY,
                )

            time.sleep(10)
            after_balances = self.get_fibers_balance()

            # Step 7: Assert balance changes match expected
            # fiber1: local_balance change (original expected: 6000000)
            assert (
                before_balances[0]["ckb"]["local_balance"]
                - after_balances[0]["ckb"]["local_balance"]
                == 6000000
            )
            assert before_balances[0]["ckb"]["offered_tlc_balance"] == 0
            assert after_balances[0]["ckb"]["offered_tlc_balance"] == 0
            assert before_balances[0]["ckb"]["received_tlc_balance"] == 0
            assert after_balances[0]["ckb"]["received_tlc_balance"] == 0

            # fiber2: local_balance change (original expected: -12000000)
            assert (
                before_balances[1]["ckb"]["local_balance"]
                - after_balances[1]["ckb"]["local_balance"]
                == -12000000
            )
            assert before_balances[1]["ckb"]["offered_tlc_balance"] == 0
            assert after_balances[1]["ckb"]["offered_tlc_balance"] == 0
            assert before_balances[1]["ckb"]["received_tlc_balance"] == 0
            assert after_balances[1]["ckb"]["received_tlc_balance"] == 0

            # fiber3: local_balance change (original expected: 6000000)
            assert (
                before_balances[2]["ckb"]["local_balance"]
                - after_balances[2]["ckb"]["local_balance"]
                == 6000000
            )
            assert before_balances[2]["ckb"]["offered_tlc_balance"] == 0
            assert after_balances[2]["ckb"]["offered_tlc_balance"] == 0
            assert before_balances[2]["ckb"]["received_tlc_balance"] == 0
            assert after_balances[2]["ckb"]["received_tlc_balance"] == 0
