"""
Test cases for send_payment payment_hash parameter.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    HashAlgorithm,
    InvoiceStatus,
    PaymentStatus,
)


class TestPaymentHash(FiberTest):
    """
    Test payment_hash parameter: non-existent hash fails; random hash causes Musig2VerifyError;
    duplicate payment (same invoice) raises Payment session already exists.
    """

    def test_payment_hash_not_exist(self):
        """
        Payment with non-existent payment_hash should fail.
        Step 1: Build fiber1->fiber2->fiber3 topology.
        Step 2: Create invoice; send payment with random payment_hash.
        Step 3: Assert payment status Failed.
        """
        # Step 1: Build fiber1->fiber2->fiber3 topology
        account_private = self.generate_account(1000)
        self.fiber3 = self.start_new_fiber(account_private)
        self.fiber3.connect_peer(self.fiber2)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(), ChannelState.CHANNEL_READY
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber3.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(), self.fiber2.get_peer_id(), ChannelState.CHANNEL_READY
        )

        # Step 2: Create invoice; send payment with random payment_hash
        invoice = self.fiber3.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(100)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        parse_invoice = self.fiber2.get_client().parse_invoice(
            {"invoice": invoice["invoice_address"]}
        )
        payment1 = self.fiber1.get_client().send_payment(
            {
                "target_pubkey": parse_invoice["invoice"]["data"]["attrs"][4][
                    "payee_public_key"
                ],
                "currency": parse_invoice["invoice"]["currency"],
                "payment_hash": self.generate_random_preimage(),
                "amount": invoice["invoice"]["amount"],
            }
        )

        # Step 3: Assert payment status Failed
        self.wait_payment_state(self.fiber1, payment1["payment_hash"], PaymentStatus.FAILED)

    def test_rand_hash_Musig2VerifyError(self):
        """
        Payment with random payment_hash causes Musig2VerifyError; channel remains ready.
        Step 1: Build topology; create invoice.
        Step 2: Send payment with random payment_hash (dry_run then real).
        Step 3: Assert payment Failed; channel state CHANNEL_READY; offered_tlc_balance=0.
        """
        account_private = self.generate_account(1000)
        self.fiber3 = self.start_new_fiber(account_private)
        self.fiber3.connect_peer(self.fiber2)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(), ChannelState.CHANNEL_READY
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber3.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(), self.fiber2.get_peer_id(), ChannelState.CHANNEL_READY
        )

        invoice = self.fiber3.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(100)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        parse_invoice = self.fiber2.get_client().parse_invoice(
            {"invoice": invoice["invoice_address"]}
        )

        self.fiber1.get_client().send_payment(
            {
                "target_pubkey": parse_invoice["invoice"]["data"]["attrs"][4][
                    "payee_public_key"
                ],
                "currency": parse_invoice["invoice"]["currency"],
                "payment_hash": self.generate_random_preimage(),
                "amount": invoice["invoice"]["amount"],
                "dry_run": True,
            }
        )
        payment1 = self.fiber1.get_client().send_payment(
            {
                "target_pubkey": parse_invoice["invoice"]["data"]["attrs"][4][
                    "payee_public_key"
                ],
                "currency": parse_invoice["invoice"]["currency"],
                "payment_hash": self.generate_random_preimage(),
                "amount": invoice["invoice"]["amount"],
            }
        )
        self.wait_payment_state(self.fiber1, payment1["payment_hash"], PaymentStatus.FAILED)
        channels = self.fiber1.get_client().list_channels({})
        assert channels["channels"][0]["state"]["state_name"] == ChannelState.CHANNEL_READY
        assert channels["channels"][0]["offered_tlc_balance"] == "0x0"

    def test_paid_hash(self):
        """
        Duplicate payment (same invoice) raises Payment session already exists.
        Step 1: Open channel; create invoice; send payment.
        Step 2: Assert invoice Paid.
        Step 3: Send payment again with same invoice; assert Payment session already exists.
        """
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(), ChannelState.CHANNEL_READY
        )
        time.sleep(1)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_invoice_state(self.fiber2, payment["payment_hash"], InvoiceStatus.PAID)

        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        expected_error_message = "Payment session already exists"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
