"""
Test cases for send_payment allow_self_payment parameter.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    PaymentStatus,
)


class TestAllowSelfPayment(FiberTest):
    """
    Test allow_self_payment parameter: self-payment (a1->b1->a1) requires allow_self_payment.
    Scenarios: a1-b1-a1 (no path), a1-b1-a2 (round-trip), a1-b1-c1-a2 (triangle).
    """

    def test_a1_to_b1_to_a1(self):
        """
        a1-b1-a1: self-payment without allow_self_payment should fail; with allow_self_payment
        and no path should fail; with path and allow_self_payment should succeed.
        Step 1: Open channel a1-b1.
        Step 2: Assert keysend/invoice to self without allow_self_payment fails with expected error.
        Step 3: Assert keysend/invoice to self with allow_self_payment but no path fails.
        Step 4: Send payment a1->b1 to establish balance; assert self-payment with allow_self_payment fails (no path).
        Step 5: Send payment a1->b1; assert success and balance.
        """
        # Step 1: Open channel a1-b1
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        time.sleep(1)

        # Step 2: Assert keysend/invoice to self without allow_self_payment fails
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {
                    "target_pubkey": self.fiber1.get_client().node_info()["node_id"],
                    "amount": hex(Amount.ckb(50)),
                    "keysend": True,
                    "dry_run": True,
                }
            )
        expected_error_message = "allow_self_payment is not enable"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        with pytest.raises(Exception) as exc_info:
            invoice = self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(Amount.ckb(10)),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node1",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                }
            )
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 3: Assert keysend/invoice to self with allow_self_payment but no path fails
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {
                    "target_pubkey": self.fiber1.get_client().node_info()["node_id"],
                    "amount": hex(Amount.ckb(50)),
                    "keysend": True,
                    "dry_run": True,
                    "allow_self_payment": True,
                }
            )
        expected_error_message = "Failed to build route"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        with pytest.raises(Exception) as exc_info:
            invoice = self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(Amount.ckb(10)),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node1",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                }
            )
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"], "allow_self_payment": True}
            )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        time.sleep(1)

        # Step 4: Send payment a1->b1 to establish balance; assert self-payment fails (no path)
        payment1 = self.fiber1.get_client().send_payment(
            {
                "target_pubkey": self.fiber2.get_client().node_info()["node_id"],
                "amount": hex(Amount.ckb(10)),
                "keysend": True,
            }
        )
        self.wait_payment_state(
            self.fiber1, payment1["payment_hash"], PaymentStatus.SUCCESS
        )
        channels = self.fiber2.get_client().list_channels({})
        assert channels["channels"][0]["local_balance"] == hex(Amount.ckb(10))
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {
                    "target_pubkey": self.fiber1.get_client().node_info()["node_id"],
                    "amount": hex(Amount.ckb(1)),
                    "keysend": True,
                    "dry_run": True,
                    "allow_self_payment": True,
                }
            )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        with pytest.raises(Exception) as exc_info:
            invoice = self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(Amount.ckb(1)),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node1",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                }
            )
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"], "allow_self_payment": True}
            )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_a1_to_b1_to_a2(self):
        """
        a1(1000)-b1(0) a2(0)-b2(1000): self-payment a1->b1->a1 via a2 requires allow_self_payment.
        Step 1: Open channels a1-b1 and b1-a1 (bidirectional), a2-b2.
        Step 2: Assert self-payment without allow_self_payment fails.
        Step 3: Assert self-payment with allow_self_payment succeeds (dry_run and real).
        """
        # Step 1: Open channels a1-b1 and b1-a1 (bidirectional), a2-b2
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        time.sleep(2)
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        time.sleep(1)

        # Step 2: Assert self-payment without allow_self_payment fails
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {
                    "target_pubkey": self.fiber1.get_client().node_info()["node_id"],
                    "amount": hex(Amount.ckb(50)),
                    "keysend": True,
                    "dry_run": True,
                }
            )
        expected_error_message = "allow_self_payment is not enable"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        with pytest.raises(Exception) as exc_info:
            invoice = self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(Amount.ckb(10)),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node1",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                }
            )
            time.sleep(1)
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        time.sleep(1)

        # Step 3: Assert self-payment with allow_self_payment succeeds (dry_run and real)
        payment1 = self.fiber1.get_client().send_payment(
            {
                "target_pubkey": self.fiber1.get_client().node_info()["node_id"],
                "amount": hex(Amount.ckb(50)),
                "keysend": True,
                "dry_run": True,
                "allow_self_payment": True,
            }
        )
        assert payment1["fee"] != "0x0"
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(10)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node1",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        payment1 = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"], "allow_self_payment": True}
        )
        self.wait_payment_state(
            self.fiber1, payment1["payment_hash"], PaymentStatus.SUCCESS
        )

    def test_a1_to_b1_to_c1_a2(self):
        """
        a1-b1-c1-a1 triangle: self-payment a1->b1->c1->a1 with allow_self_payment.
        Step 1: Build topology a1-b1-c1-a1.
        Step 2: Retry self-payment until 3 successes (flaky route).
        """
        # Step 1: Build topology a1-b1-c1-a1
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.fiber3.connect_peer(self.fiber2)
        self.fiber3.connect_peer(self.fiber1)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber3.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            self.fiber3.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.fiber3.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )

        # Step 2: Retry self-payment until 3 successes (flaky route)
        time.sleep(1)
        success_size = 0
        try_size = 0
        while success_size < 3:
            try_size += 1
            assert try_size < 30
            try:
                payment1 = self.fiber1.get_client().send_payment(
                    {
                        "target_pubkey": self.fiber1.get_client().node_info()[
                            "node_id"
                        ],
                        "amount": hex(Amount.ckb(0.6)),
                        "keysend": True,
                        "allow_self_payment": True,
                    }
                )
                time.sleep(3)
                self.wait_payment_state(
                    self.fiber1, payment1["payment_hash"], PaymentStatus.SUCCESS
                )
                success_size += 1
            except Exception:
                continue

    def test_a1_to_b1_to_c1_a2_2(self):
        """
        a1-b1-c1-a1 triangle: single self-payment with allow_self_payment.
        Step 1: Build topology a1-b1-c1-a1.
        Step 2: Send self-payment with allow_self_payment; assert success.
        """
        # Step 1: Build topology a1-b1-c1-a1
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.fiber3.connect_peer(self.fiber2)
        self.fiber3.connect_peer(self.fiber1)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber3.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            self.fiber3.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.fiber3.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )

        # Step 2: Send self-payment with allow_self_payment; assert success
        time.sleep(1)
        payment1 = self.fiber1.get_client().send_payment(
            {
                "target_pubkey": self.fiber1.get_client().node_info()["node_id"],
                "amount": hex(Amount.ckb(0.6)),
                "keysend": True,
                "allow_self_payment": True,
            }
        )
        self.wait_payment_state(
            self.fiber1, payment1["payment_hash"], PaymentStatus.SUCCESS
        )
