"""
Test cases for send_payment dry_run parameter and max_fee_amount.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    HashAlgorithm,
    InvoiceStatus,
    PaymentStatus,
)


class TestDryRun(FiberTest):
    """
    Test dry_run parameter: returns fee without executing; max_fee_amount with dry_run fee.
    """

    def test_dry_run(self):
        """
        dry_run returns fee; invoice stays Open; get_payment fails; max_fee_amount < fee rejects.
        Step 1: Build fiber1->fiber2->fiber3 topology and open channels.
        Step 2: Create invoice, send payment with dry_run; assert fee returned.
        Step 3: Assert invoice still Open; get_payment fails (no session).
        Step 4: Assert max_fee_amount < dry_run fee rejects.
        Step 5: Send real payment with max_fee_amount = dry_run fee; assert success.
        """
        # Step 1: Build fiber1->fiber2->fiber3 topology and open channels
        account_private = self.generate_account(1000)
        self.fiber3 = self.start_new_fiber(account_private)
        self.fiber3.connect_peer(self.fiber2)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber3.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )

        # Step 2: Create invoice, send payment with dry_run; assert fee returned
        invoice = self.fiber3.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(100)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        self.fiber2.get_client().parse_invoice(
            {"invoice": invoice["invoice_address"]}
        )
        payment1 = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "dry_run": True,
            }
        )
        assert payment1["fee"] == hex(Amount.ckb(0.1))

        # Step 3: Assert invoice still Open; get_payment fails (no session)
        self.wait_invoice_state(
            self.fiber3, payment1["payment_hash"], InvoiceStatus.OPEN
        )
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().get_payment(
                {"payment_hash": payment1["payment_hash"]}
            )
        expected_error_message = "Payment session not found"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 4: Assert max_fee_amount < dry_run fee rejects
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {
                    "invoice": invoice["invoice_address"],
                    "max_fee_amount": hex(int(payment1["fee"], 16) - 1),
                }
            )
        expected_error_message = "no path found"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 5: Send real payment with max_fee_amount = dry_run fee; assert success
        payment1 = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_amount": payment1["fee"],
            }
        )
        self.wait_payment_state(
            self.fiber1, payment1["payment_hash"], PaymentStatus.SUCCESS
        )

    def test_mutil_channel(self):
        """
        dry_run with multi-channel topology; fee reflects routing.
        Step 1: Build fiber1->fiber2->fiber3 with updated channel fee.
        Step 2: Send dry_run keysend; assert fee returned.
        """
        # Step 1: Build fiber1->fiber2->fiber3 with updated channel fee
        account_private = self.generate_account(2000)
        self.fiber3 = self.start_new_fiber(account_private)
        self.fiber3.connect_peer(self.fiber2)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.fiber2.get_client().update_channel(
            {
                "channel_id": self.fiber1.get_client().list_channels({})["channels"][
                    0
                ]["channel_id"],
                "tlc_fee_proportional_millionths": hex(2000),
            }
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber3.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
        )
        time.sleep(1)

        # Step 2: Send dry_run keysend; assert fee returned
        payment = self.fiber1.get_client().send_payment(
            {
                "target_pubkey": self.fiber3.get_client().node_info()["node_id"],
                "amount": hex(Amount.ckb(10)),
                "keysend": True,
                "dry_run": True,
            }
        )
        assert payment["fee"] == hex(Amount.ckb(0.01))
