"""
Test cases for send_payment with used preimage.
When an invoice is created with a payment_preimage that was already used, new_invoice should reject.
"""
import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Currency, HashAlgorithm, PaymentStatus


class TestUsedPreimage(FiberTest):
    """
    Test that new_invoice rejects when payment_preimage was already used in a previous invoice.
    """

    def test_used_preimage(self):
        """
        Verify that reusing the same payment_preimage for a new invoice fails with "invoice already exists".
        Step 1: Open channel between fiber1 and fiber2.
        Step 2: Create invoice with payment_preimage and pay it successfully.
        Step 3: Attempt to create another invoice with the same payment_preimage.
        Step 4: Assert new_invoice raises with "invoice already exists".
        """
        # Step 1: Open channel between fiber1 and fiber2
        self.open_channel(
            self.fiber1, self.fiber2,
            Amount.ckb(1000), Amount.ckb(1000)
        )

        # Step 2: Create invoice with payment_preimage and pay it successfully
        payment_preimage = self.generate_random_preimage()
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS
        )

        # Step 3: Attempt to create another invoice with the same payment_preimage
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().new_invoice(
                {
                    "amount": hex(Amount.ckb(1)),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": payment_preimage,
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )

        # Step 4: Assert new_invoice raises with "invoice already exists"
        expected_error_message = "invoice already exists"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
