# import time
#
# from framework.basic_fiber import FiberTest
#
#
# class MutilToOneTest(FiberTest):
#     # debug = True
#     start_fiber_config = {"fiber_funding_timeout_seconds": 10}
#
#     def test_mutil_to_one(self):
#         n = 5
#         for i in range(n):
#             self.start_new_fiber(
#                 self.generate_account(
#                     10000, self.fiber1.account_private, 10000 * 100000000
#                 )
#             )
#         self.faucet(
#             self.fiber1.account_private,
#             0,
#             self.fiber1.account_private,
#             10000 * 100000000,
#         )
#         self.open_channel(
#             self.fiber1,
#             self.fiber2,
#             1000 * 100000000,
#             0,
#             0,
#             0,
#             self.get_account_udt_script(self.fiber1.account_private),
#         )
#         for i in range(n):
#             self.open_channel(
#                 self.new_fibers[i],
#                 self.fiber1,
#                 1000 * 100000000,
#                 0,
#                 0,
#                 0,
#                 self.get_account_udt_script(self.fiber1.account_private),
#             )
#
#         n = 20
#         invoices = []
#         for i in range(n):
#             invoice = self.fiber2.get_client().new_invoice(
#                 {
#                     "amount": hex(100 * 100000000),
#                     "currency": "Fibd",
#                     "description": "test invoice generated by node3",
#                     # "expiry": "0xe10",
#                     # "final_expiry_delta": hex(57600000),
#                     "payment_preimage": self.generate_random_preimage(),
#                     "udt_type_script": self.get_account_udt_script(
#                         self.fiber1.account_private
#                     ),
#                 }
#             )
#             invoices.append(invoice)
#             # invoice += self.send_invoice_payment(self.fiber1,self.fiber2,400*100000000,self.get_account_udt_script(self.fiber1.account_private))
#         for i in range(n):
#             try:
#                 fiber = self.new_fibers[i % len(self.new_fibers)]
#                 fiber.get_client().send_payment(
#                     {
#                         "invoice": invoices[i]["invoice_address"],
#                     }
#                 )
#             except Exception as e:
#                 pass
#         time.sleep(1)
#         self.fiber2.get_client().disconnect_peer({"pubkey": self.fiber1.get_pubkey()})
#
#     def test_fiber1_shutdown_channels(self):
#         channels = self.fiber1.get_client().list_channels({})
#         for channel in channels["channels"]:
#             self.fiber1.get_client().shutdown_channel(
#                 {
#                     "channel_id": channel["channel_id"],
#                     "force": True,
#                 }
#             )
#
#     def test_list_balance(self):
#         n = 5
#         for i in range(n):
#             self.start_new_mock_fiber("")
#         self.get_fiber_graph_balance()
#         # self.fiber1.connect_peer(self.fiber2)
#
#     def test_generate_epoch(self):
#         self.node.getClient().generate_epochs("0x2")
#
#     def test_fiber2(self):
#         for i in range(5):
#             self.start_new_mock_fiber("")
#         self.fibers[1].get_client().list_channels({})
#         # self.fiber2.get_client().node_info()
#
#     def test_graph(self):
#         graph_nodes = self.fiber1.get_client().graph_channels({})
#         print(graph_nodes)
#         # self.fiber1.connect_peer(self.fiber2)
#
#
# # 0xed588483f457723b6d4f06fbc03aad66c50d08a5ae2679807d978ffddc1da70500000000
