"""
Test cases for Fiber issue #670: add_tlc with invoice and expiry.
Requirement: https://github.com/nervosnetwork/fiber/issues/670
"""
import time

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Currency
from framework.test_fiber import FiberConfigPath


class TestIssue670(FiberTest):
    """
    Test issue #670: add_tlc RPC with invoice payment_hash and expiry.
    Uses a third fiber node and adds TLC manually for the invoice.
    """
    fiber_version = FiberConfigPath.CURRENT_DEV_DEBUG

    def test_issue_670(self):
        """
        Add TLC for an invoice on a channel and verify invoice/TLC flow.
        Step 1: Start third fiber and open channel fiber1-fiber2.
        Step 2: Create invoice on fiber3 (fibers[2]) with amount and preimage.
        Step 3: Add TLC on fiber1's channel with invoice payment_hash and expiry.
        """
        # Step 1: Start third fiber and open channel fiber1-fiber2
        self.start_new_fiber(self.generate_account(1000))
        self.open_channel(
            self.fiber1, self.fiber2, Amount.ckb(1000), Amount.ckb(1000)
        )

        # Step 2: Create invoice on fiber3 (fibers[2]) with amount and preimage
        preimage = self.generate_random_preimage()
        invoice = (
            self.fibers[2]
            .get_client()
            .new_invoice(
                {
                    "amount": hex(Amount.ckb(300)),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": preimage,
                    "hash_algorithm": "ckb_hash",
                }
            )
        )

        # Step 3: Add TLC on fiber1's channel with invoice payment_hash and expiry
        channel_id = self.fiber1.get_client().list_channels({})["channels"][0][
            "channel_id"
        ]
        expiry_ms = (int(time.time()) + 360000) * 1000
        self.fiber1.get_client().add_tlc(
            {
                "channel_id": channel_id,
                "amount": hex(Amount.ckb(300)),
                "payment_hash": invoice["invoice"]["data"]["payment_hash"],
                "expiry": hex(expiry_ms),
                "hash_algorithm": "ckb_hash",
            }
        )
