import time

import pytest

from framework.basic_fiber import FiberTest
from framework.config import DEFAULT_MIN_DEPOSIT_CKB


class LinkedTest(FiberTest):
    # FiberTest.debug = True

    def test_unlink_peer(self):
        """
        1. open channel with unlinked peer id
            Returns: pubkey not found
        """
        with pytest.raises(Exception) as exc_info:
            ret = self.fiber1.get_client().open_channel(
                {
                    "peer_id": "QmQTR428wfY8s5wFTwU6ZaNBCJg1RwWbDFdP2r1WPNBQX1",
                    "funding_amount": hex(1000 * 100000000),
                    "public": True,
                    "funding_udt_type_script": {
                        "code_hash": self.udtContract.get_code_hash(
                            True, self.node.rpcUrl
                        ),
                        "hash_type": "type",
                        "args": self.udtContract.get_owner_arg_by_lock_arg(
                            self.account1["lock_arg"]
                        ),
                    },
                    # "tlc_fee_proportional_millionths": "0x4B0",
                }
            )

        expected_error_message = "feature not found"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_linked_peer(self):
        """
        open channel with lined peer
        1. open_channel
        2. new_invoice
        3. send_payment
        4. shutdown_channel
        Returns:
        """
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(200 * 100000000),
                "public": True,
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(), "CHANNEL_READY", 120
        )

        # transfer
        payment_preimage = self.generate_random_preimage()
        invoice_balance = 100 * 100000000
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], "Success")
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        before_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        # shut down
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": self.account1["lock_arg"],
                },
                "fee_rate": "0x3FC",
            }
        )
        # todo wait close tx commit
        tx_hash = self.wait_and_check_tx_pool_fee(1000, False, 100)
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        after_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        print("before_balance1:", before_balance1)
        print("before_balance2:", before_balance2)
        print("after_balance1:", after_balance1)
        print("after_balance2:", after_balance2)
        assert (
            after_balance2 - before_balance2
        ) * 100000000 == 100 * 100000000 + DEFAULT_MIN_DEPOSIT_CKB
