"""
Test open_channel funding_fee_rate: too small, too big, overflow, non-default, gt balance.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.config import DEFAULT_MIN_DEPOSIT_CKB
from framework.constants import Amount, ChannelState, Currency, FeeRate, Timeout


class TestFundingFeeRate(FiberTest):
    """
    Test open_channel funding_fee_rate validation and behavior.
    """

    @pytest.mark.skip("todo")
    def test_funding_fee_rate_none(self):
        """
        funding_fee_rate is none (todo: implement).
        Step 1: (Not implemented.)
        """

    def test_funding_fee_rate_too_min(self):
        """
        funding_fee_rate = 1 should be rejected (less than 1000).
        Step 1: Call open_channel with funding_fee_rate hex(1).
        Step 2: Assert error message "Funding fee rate is less than 1000".
        """
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().open_channel(
                {
                    "peer_id": self.fiber2.get_peer_id(),
                    "funding_amount": hex(Amount.ckb(200)),
                    "public": True,
                    "funding_fee_rate": hex(1),
                }
            )
        expected_error_message = "Funding fee rate is less than 1000"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_funding_fee_rate_too_big(self):
        """
        funding_fee_rate == int.max: open channel and check tx pool fee (early return after wait).
        Step 1: Open channel with funding_fee_rate 0xffff...ff.
        Step 2: Wait for tx pool fee and get tx message; return (remaining steps skipped).
        """
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
                "funding_fee_rate": "0xffffffffffffffff",
            }
        )
        tx_hash = self.wait_and_check_tx_pool_fee(
            int("0xffffffffffffffff", 16), False
        )
        tx_message = self.get_tx_message(tx_hash)
        assert tx_message is not None
        return

    def test_funding_fee_rate_over_flow(self):
        """
        funding_fee_rate hex overflow (too many digits) should be rejected as Invalid params.
        Step 1: Connect peer, call open_channel with funding_fee_rate 0xff...f (overflow hex).
        Step 2: Assert error message "Invalid params".
        """
        self.fiber1.connect_peer(self.fiber2)
        time.sleep(5)
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().open_channel(
                {
                    "peer_id": self.fiber2.get_peer_id(),
                    "funding_amount": hex(Amount.ckb(200)),
                    "public": True,
                    "funding_fee_rate": "0xfffffffffffffffffffffffff",
                }
            )
        expected_error_message = "Invalid params"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_funding_fee_rate_not_eq_default(self):
        """
        funding_fee_rate != default: open channel, send payment, shutdown, assert balance change.
        Step 1: Open channel with funding_fee_rate 2000, wait CHANNEL_READY.
        Step 2: Create invoice and send payment, wait, assert balance change.
        Step 3: Shutdown with close_script and fee_rate, wait, assert after_balance2 change.
        """
        self.fiber1.connect_peer(self.fiber2)
        time.sleep(5)
        funding_fee_rate = FeeRate.MEDIUM
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
                "funding_fee_rate": hex(funding_fee_rate),
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        time.sleep(5)
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(100)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})
        self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        time.sleep(10)
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )
        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        channel_id = channels["channels"][0]["channel_id"]
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": channel_id,
                "close_script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": self.account1["lock_arg"],
                },
                "fee_rate": "0x3FC",
            }
        )
        time.sleep(20)
        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        assert (
            after_balance2 - before_balance2
        ) * Amount.CKB == Amount.ckb(100) + DEFAULT_MIN_DEPOSIT_CKB

    @pytest.mark.skip("https://github.com/nervosnetwork/fiber/issues/276")
    def test_ckb_check_funding_fee_rate(self):
        """
        Verify CKB funding tx uses specified funding_fee_rate (skipped: issue 276).
        Step 1: Open channel with funding_fee_rate 2000.
        Step 2: wait_and_check_tx_pool_fee(2000).
        """
        funding_fee_rate = FeeRate.MEDIUM
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
                "funding_fee_rate": hex(funding_fee_rate),
            }
        )
        self.wait_and_check_tx_pool_fee(funding_fee_rate)

    def test_funding_fee_rate_gt_balance(self):
        """
        funding_fee_rate so high that account cannot afford: no channel created.
        Step 1: Prepare account3, start fiber, open channel with funding_fee_rate 0xffffffffff.
        Step 2: Wait briefly; assert channels list is empty.
        """
        account3_private_key = (
            "0x200c06bfd800d27397002dca6fb0993d5ba6399b4238b2f29ee9deb97593d2b1"
        )
        account3 = self.Ckb_cli.util_key_info_by_private_key(account3_private_key)
        tx_hash = self.Ckb_cli.wallet_transfer_by_private_key(
            self.Config.ACCOUNT_PRIVATE_1,
            account3["address"]["testnet"],
            1000,
            self.node.rpcUrl,
        )
        self.Miner.miner_until_tx_committed(self.node, tx_hash)
        account3_private_key = self.generate_account(1000)
        fiber = self.start_new_fiber(account3_private_key)
        fiber.connect_peer(self.fiber2)
        time.sleep(3)
        fiber.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(990)),
                "public": True,
                "funding_fee_rate": "0xffffffffff",
            }
        )
        time.sleep(1)
        channels = fiber.get_client().list_channels({})
        assert channels["channels"] == []
