import time

import pytest

from framework.basic_fiber import FiberTest


class TestTlcFeeProportionalMillionths(FiberTest):

    def test_tlc_fee_proportional_millionths_default(self):
        """
        tlc_fee_proportional_millionths : none
        Returns:
        """
        account3_private_key = self.generate_account(1000)
        new_fiber = self.start_new_fiber(account3_private_key)
        time.sleep(3)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(3)
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(200 * 100000000),
                "public": True,
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        temporary_channel_id = self.fiber2.get_client().open_channel(
            {
                "pubkey": new_fiber.get_pubkey(),
                "funding_amount": hex(1000 * 100000000),
                "public": True,
                # "tlc_min_value": hex(2 * 100000000)
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_pubkey(), "CHANNEL_READY", 120
        )
        invoice_balance = hex(100 * 100000000)
        payment_preimage = self.generate_random_preimage()
        invoice = new_fiber.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel_12 = self.fiber1.get_client().list_channels({})
        before_channel_32 = new_fiber.get_client().list_channels({})
        time.sleep(10)
        self.fiber2.get_client().graph_channels()
        self.fiber2.get_client().graph_nodes()
        self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        time.sleep(10)
        after_channel_12 = self.fiber1.get_client().list_channels({})
        after_channel_32 = new_fiber.get_client().list_channels({})

        print("before_channel_12:", before_channel_12)
        print("before_channel_32:", before_channel_32)
        print("after_channel_12:", after_channel_12)
        print("after_channel_32:", after_channel_32)

        assert int(before_channel_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == (int(invoice_balance, 16) + int(int(invoice_balance, 16) * 0.001))

        assert int(after_channel_32["channels"][0]["local_balance"], 16) - int(
            before_channel_32["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

    def test_tlc_fee_proportional_millionths_overflow(self):
        """
        tlc_fee_proportional_millionths > int.max
        Returns:
        """
        with pytest.raises(Exception) as exc_info:
            temporary_channel_id = self.fiber2.get_client().open_channel(
                {
                    "pubkey": self.fiber1.get_pubkey(),
                    "funding_amount": hex(1000 * 100000000),
                    "public": True,
                    # "tlc_min_value": hex(2 * 100000000)
                    # "funding_fee_rate": "0xffff",
                    "tlc_fee_proportional_millionths": "0x1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
                }
            )
        expected_error_message = "Invalid params"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_tlc_fee_proportional_millionths_100_100000000_1000_1000(self):
        """
        tlc_fee_proportional_millionths ：100 * 100000000 * 1000 * 1000
        发送 1，收取100ckb的手续费
        Returns:
        """
        temporary_channel_id = self.fiber2.get_client().open_channel(
            {
                "pubkey": self.fiber1.get_pubkey(),
                "funding_amount": hex(1000 * 100000000),
                "public": True,
                # "tlc_min_value": hex(2 * 100000000)
                # "funding_fee_rate": "0xffff",
                "tlc_fee_proportional_millionths": hex(100 * 100000000 * 1000 * 1000),
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(), self.fiber1.get_pubkey(), "CHANNEL_READY", 120
        )
        channel = self.fiber1.get_client().list_channels({})
        assert channel["channels"][0]["tlc_fee_proportional_millionths"] == "0x3e8"
        channel = self.fiber2.get_client().list_channels({})
        assert channel["channels"][0]["tlc_fee_proportional_millionths"] == hex(
            100 * 100000000 * 1000000
        )
        fiber3 = self.start_new_fiber(self.generate_account(10000))
        fiber3.connect_peer(self.fiber2)
        time.sleep(1)
        fiber3.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(1000 * 100000000),
                "public": True,
                # "tlc_min_value": hex(2 * 100000000)
                # "funding_fee_rate": "0xffff",
                "tlc_fee_proportional_millionths": "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            }
        )
        self.wait_for_channel_state(
            fiber3.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        self.send_payment(fiber3, self.fiber1, 1)

    def test_ckb_tlc_fee_proportional_millionths_not_eq_default(self):
        """
        tlc_fee_proportional_millionths != default
        - node1 send node3
            node1 - node2（fee = 1000）
        - node3 send node1
            node3- node2（fee = 1000000）
        Returns:
        """
        account3_private_key = self.generate_account(1000)
        new_fiber = self.start_new_fiber(account3_private_key)
        time.sleep(3)
        self.fiber2.connect_peer(new_fiber)

        # self.fiber3.connect_peer(self.fiber2)
        time.sleep(3)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(3)
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(500 * 100000000),
                "public": True,
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": hex(1000000),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        fiber2_tlc_fee = 1000000
        temporary_channel_id = self.fiber2.get_client().open_channel(
            {
                "pubkey": new_fiber.get_pubkey(),
                "funding_amount": hex(1000 * 100000000),
                "public": True,
                "tlc_fee_proportional_millionths": hex(fiber2_tlc_fee),
                # "tlc_min_value": hex(2 * 100000000)
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_pubkey(), "CHANNEL_READY", 120
        )
        invoice_balance = hex(100 * 100000000)
        payment_preimage = self.generate_random_preimage()
        invoice = new_fiber.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel_12 = self.fiber1.get_client().list_channels({})
        before_channel_32 = new_fiber.get_client().list_channels({})
        time.sleep(1)
        self.fiber2.get_client().graph_channels()
        self.fiber2.get_client().graph_nodes()
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"], "max_fee_rate": hex(1000000)}
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"])
        after_channel_12 = self.fiber1.get_client().list_channels({})
        after_channel_32 = new_fiber.get_client().list_channels({})

        print("before_channel_12:", before_channel_12)
        print("before_channel_32:", before_channel_32)
        print("after_channel_12:", after_channel_12)
        print("after_channel_32:", after_channel_32)

        assert int(before_channel_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == (
            int(invoice_balance, 16)
            + int(int(invoice_balance, 16) * fiber2_tlc_fee / 1000000)
        )

        assert int(after_channel_32["channels"][0]["local_balance"], 16) - int(
            before_channel_32["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)
        invoice_balance = hex(1 * 1000000)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        time.sleep(1)
        payment = new_fiber.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_rate": hex(1000000),
            }
        )
        self.wait_payment_state(new_fiber, payment["payment_hash"], "Success", 120)
        after_channel_2_12 = self.fiber1.get_client().list_channels({})
        after_channel_2_32 = new_fiber.get_client().list_channels({})
        new_fiber.get_client().graph_nodes()
        print("after_channel_2_12:", after_channel_2_12)
        print("after_channel_2_32:", after_channel_2_32)
        # assert
        assert (
            int(after_channel_32["channels"][0]["local_balance"], 16)
            - int(after_channel_2_32["channels"][0]["local_balance"], 16)
            == int(invoice_balance, 16) + int(invoice_balance, 16) * 1000 / 1000000
        )

        assert int(after_channel_2_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

    def test_normal_fee(self):
        """
        1-2-3
        1 send 3 fee= 1000000
        3 send 1 fee=1000
        Returns:

        """
        self.start_new_fiber(self.generate_account(1000))
        self.open_channel(
            self.fibers[0],
            self.fibers[1],
            1000 * 100000000,
            1,
            fiber1_fee=1000,
            fiber2_fee=1000,
        )
        self.open_channel(
            self.fibers[1],
            self.fibers[2],
            1000 * 100000000,
            1,
            fiber1_fee=1000000,
            fiber2_fee=1000,
        )
        time.sleep(5)
        payment_hash = self.send_payment(self.fibers[0], self.fibers[2], 10 * 100000000)
        payment = (
            self.fibers[0].get_client().get_payment({"payment_hash": payment_hash})
        )
        assert payment["fee"] == hex(int(10 * 100000000 * 1000000 / 1000000))
        payment_hash = self.send_payment(self.fibers[2], self.fibers[0], 1 * 100000000)
        payment = (
            self.fibers[2].get_client().get_payment({"payment_hash": payment_hash})
        )
        assert payment["fee"] == hex(int(1 * 100000000 * 1000 / 1000000))
        channels1 = self.fiber1.get_client().list_channels({})
        channels2 = self.fibers[2].get_client().list_channels({})
        assert channels1["channels"][0]["local_balance"] == hex(98100000000)
        assert channels2["channels"][0]["local_balance"] == hex(899900001)

    # def test_fee_mutil(self):
    #     self.start_new_fiber(self.generate_account(10000))
    #     self.start_new_fiber(self.generate_account(10000))
    #
    #     self.open_channel(self.fibers[0], self.fibers[1], 1000 * 100000000, 1, fiber1_fee=1000, fiber2_fee=1000)
    #     self.open_channel(self.fibers[1], self.fibers[2], 1000 * 100000000, 1, fiber1_fee=1000000, fiber2_fee=1000)
    #     self.open_channel(self.fibers[2], self.fibers[3], 1000 * 100000000, 1, fiber1_fee=2000000, fiber2_fee=1000)
    #     self.open_channel(self.fibers[3], self.fibers[0], 1000 * 100000000, 1, fiber1_fee=3000000, fiber2_fee=1000)
    #     for i in range(100):
    #         self.send_payment(self.fibers[0], self.fibers[0], 1 * 100000000)
    #     # (100000000 * (1+ 3000000/ 1000000) )   * (1+ 2000000/ 1000000)

    def test_tlc_fee_proportional_millionths_max(self):
        account3_private_key = self.generate_account(1000)
        new_fiber = self.start_new_fiber(account3_private_key)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(3)
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(20000 * 100000000),
                "public": True,
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": hex(1000000),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        fiber2_tlc_fee = 340282366
        temporary_channel_id = self.fiber2.get_client().open_channel(
            {
                "pubkey": new_fiber.get_pubkey(),
                "funding_amount": hex(10000 * 100000000),
                "public": True,
                "tlc_fee_proportional_millionths": hex(fiber2_tlc_fee),
                # "tlc_min_value": hex(2 * 100000000)
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_pubkey(), "CHANNEL_READY", 120
        )
        invoice_balance = hex(1 * 100000000)
        payment_preimage = self.generate_random_preimage()
        invoice = new_fiber.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel_12 = self.fiber1.get_client().list_channels({})
        before_channel_32 = new_fiber.get_client().list_channels({})
        time.sleep(10)
        self.fiber2.get_client().graph_channels()
        self.fiber2.get_client().graph_nodes()
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_rate": hex(100000000),
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"])
        after_channel_12 = self.fiber1.get_client().list_channels({})
        after_channel_32 = new_fiber.get_client().list_channels({})

        print("before_channel_12:", before_channel_12)
        print("before_channel_32:", before_channel_32)
        print("after_channel_12:", after_channel_12)
        print("after_channel_32:", after_channel_32)

        assert int(before_channel_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == (
            int(invoice_balance, 16)
            + int(int(invoice_balance, 16) * fiber2_tlc_fee / 1000000)
        )

        assert int(after_channel_32["channels"][0]["local_balance"], 16) - int(
            before_channel_32["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)
        invoice_balance = hex(1 * 1000000)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        time.sleep(1)
        payment = new_fiber.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_amount": hex(1000 * 100000000),
            }
        )
        self.wait_payment_state(new_fiber, payment["payment_hash"], "Success", 120)
        after_channel_2_12 = self.fiber1.get_client().list_channels({})
        after_channel_2_32 = new_fiber.get_client().list_channels({})
        new_fiber.get_client().graph_nodes()
        print("after_channel_2_12:", after_channel_2_12)
        print("after_channel_2_32:", after_channel_2_32)
        # assert
        assert (
            int(after_channel_32["channels"][0]["local_balance"], 16)
            - int(after_channel_2_32["channels"][0]["local_balance"], 16)
            == int(invoice_balance, 16) + int(invoice_balance, 16) * 1000 / 1000000
        )

        assert int(after_channel_2_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

    def test_udt_tlc_fee_proportional_millionths_not_eq_default(self):
        """
        tlc_fee_proportional_millionths != default
        Returns:
        """

        account3_private_key = self.generate_account(
            1000, self.Config.ACCOUNT_PRIVATE_1, 1000 * 100000000
        )
        new_fiber = self.start_new_fiber(account3_private_key)
        time.sleep(3)
        self.fiber2.connect_peer(new_fiber)
        self.faucet(
            self.fiber2.account_private,
            0,
            self.fiber1.account_private,
            1000 * 100000000,
        )
        self.faucet(
            self.fiber1.account_private,
            0,
            self.fiber1.account_private,
            1000 * 100000000,
        )
        account1_cells = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        account2_cells = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )
        print("account1:", account1_cells)
        print("account2:", account2_cells)
        tx_hash = self.Ckb_cli.wallet_transfer_by_private_key(
            self.Config.ACCOUNT_PRIVATE_2,
            self.account1["address"]["testnet"],
            10000,
            self.node.rpcUrl,
        )
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        time.sleep(3)
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(200 * 100000000),
                "public": True,
                # "funding_fee_rate": "0xffff",
                "tlc_fee_proportional_millionths": hex(1000000),
                "funding_udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        fiber2_tlc_fee = 1000000
        temporary_channel_id = self.fiber2.get_client().open_channel(
            {
                "pubkey": new_fiber.get_pubkey(),
                "funding_amount": hex(1000 * 100000000),
                "public": True,
                "tlc_fee_proportional_millionths": hex(fiber2_tlc_fee),
                "funding_udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
                # "tlc_min_value": hex(2 * 100000000)
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_pubkey(), "CHANNEL_READY", 120
        )
        invoice_balance = hex(100 * 100000000)
        payment_preimage = self.generate_random_preimage()
        invoice = new_fiber.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        before_channel_12 = self.fiber1.get_client().list_channels({})
        before_channel_32 = new_fiber.get_client().list_channels({})
        time.sleep(10)
        self.fiber2.get_client().graph_channels()
        self.fiber2.get_client().graph_nodes()
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"], "max_fee_rate": hex(1000000)}
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"])
        after_channel_12 = self.fiber1.get_client().list_channels({})
        after_channel_32 = new_fiber.get_client().list_channels({})

        print("before_channel_12:", before_channel_12)
        print("before_channel_32:", before_channel_32)
        print("after_channel_12:", after_channel_12)
        print("after_channel_32:", after_channel_32)

        assert int(before_channel_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == (
            int(invoice_balance, 16)
            + int(int(invoice_balance, 16) * fiber2_tlc_fee / 1000000)
        )

        assert int(after_channel_32["channels"][0]["local_balance"], 16) - int(
            before_channel_32["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)
        invoice_balance = hex(1 * 100000000)
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        time.sleep(1)
        payment = new_fiber.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_amount": hex(1000 * 100000000),
            }
        )
        time.sleep(5)
        new_fiber.get_client().get_payment({"payment_hash": payment["payment_hash"]})
        after_channel_2_12 = self.fiber1.get_client().list_channels({})
        after_channel_2_32 = new_fiber.get_client().list_channels({})
        new_fiber.get_client().graph_nodes()
        print("after_channel_2_12:", after_channel_2_12)
        print("after_channel_2_12:", after_channel_2_32)
        # assert
        assert (
            int(after_channel_32["channels"][0]["local_balance"], 16)
            - int(after_channel_2_32["channels"][0]["local_balance"], 16)
            == int(invoice_balance, 16) + int(invoice_balance, 16) * 1000 / 1000000
        )

        assert int(after_channel_2_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

    def test_ckb_tlc_fee_proportional_millionths_is_zero(self):
        """
        tlc_fee_proportional_millionths == 0

        Returns:
        """
        account3_private_key = self.generate_account(1000)
        new_fiber = self.start_new_fiber(account3_private_key)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(1)
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(500 * 100000000),
                "public": True,
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": hex(1000000),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        fiber2_tlc_fee = 0
        temporary_channel_id = self.fiber2.get_client().open_channel(
            {
                "pubkey": new_fiber.get_pubkey(),
                "funding_amount": hex(1000 * 100000000),
                "public": True,
                "tlc_fee_proportional_millionths": hex(fiber2_tlc_fee),
                # "tlc_min_value": hex(2 * 100000000)
                # "funding_fee_rate": "0xffff",
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_pubkey(), "CHANNEL_READY", 120
        )
        payment_hash = self.send_payment(self.fiber1, new_fiber, 100 * 100000000)
        payment = self.fiber1.get_client().get_payment({"payment_hash": payment_hash})
        assert payment["fee"] == "0x0"
