"""
Test open_channel with linked vs unlinked peer: unlinked peer_id yields error; linked peer full flow.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.config import DEFAULT_MIN_DEPOSIT_CKB
from framework.constants import Amount, ChannelState, Currency, HashAlgorithm, PaymentStatus, Timeout


class LinkedTest(FiberTest):
    """
    Test open_channel against linked vs unlinked peer: unlinked returns 'feature not found';
    linked peer: open_channel, new_invoice, send_payment, shutdown_channel.
    """

    def test_unlink_peer(self):
        """
        Open channel with unlinked peer_id should raise error containing "feature not found".
        Step 1: Call open_channel with a fake/unlinked peer_id.
        Step 2: Assert error message contains "feature not found".
        """
        # Step 1: Call open_channel with unlinked peer_id
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().open_channel(
                {
                    "peer_id": "QmQTR428wfY8s5wFTwU6ZaNBCJg1RwWbDFdP2r1WPNBQX1",
                    "funding_amount": hex(Amount.ckb(1000)),
                    "public": True,
                    "funding_udt_type_script": {
                        "code_hash": self.udtContract.get_code_hash(
                            True, self.node.rpcUrl
                        ),
                        "hash_type": "type",
                        "args": self.udtContract.get_owner_arg_by_lock_arg(
                            self.account1["lock_arg"]
                        ),
                    },
                }
            )

        # Step 2: Assert error message contains "feature not found"
        expected_error_message = "feature not found"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_linked_peer(self):
        """
        Open channel with linked peer: open_channel, new_invoice, send_payment, shutdown_channel; assert balance.
        Step 1: Open channel, wait CHANNEL_READY.
        Step 2: Create invoice and send payment; assert balance change.
        Step 3: Shutdown channel; assert CKB balance change.
        """
        # Step 1: Open channel and wait CHANNEL_READY
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice and send payment; assert balance change
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(100)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        # Step 3: Shutdown channel; assert CKB balance
        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        before_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": self.account1["lock_arg"],
                },
                "fee_rate": hex(1020),  # 0x3FC
            }
        )
        tx_hash = self.wait_and_check_tx_pool_fee(1000, False, 100)
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        after_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        assert (
            after_balance2 - before_balance2
        ) * Amount.CKB == Amount.ckb(100) + DEFAULT_MIN_DEPOSIT_CKB
