"""
Test cases for open_channel tlc_min_value parameter.
Covers: none (default 0), non-zero limit, gt funding_amount, CKB/UDT.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.config import DEFAULT_MIN_DEPOSIT_CKB, DEFAULT_MIN_DEPOSIT_UDT
from framework.constants import (
    Amount,
    ChannelState,
    FeeRate,
    PaymentStatus,
    Timeout,
)


class TestTlcMinValue(FiberTest):
    """
    Test open_channel tlc_min_value: default (none), non-zero, gt funding_amount, CKB/UDT.
    """

    def test_tlc_min_value_none(self):
        """
        tlc_min_value = none (default 0); open channel, pay, shutdown, assert balance change.
        Step 1: Open channel without tlc_min_value, wait CHANNEL_READY.
        Step 2: Create invoice and send payment, wait and assert balance.
        Step 3: Shutdown channel and assert on-chain balance.
        """
        # Step 1: Open channel without tlc_min_value, wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        # Step 2: Create invoice and send payment, wait and assert balance
        time.sleep(5)
        self.fiber1.get_client().graph_channels()
        self.fiber1.get_client().graph_nodes()
        payment_preimage = self.generate_random_preimage()
        channels = self.fiber1.get_client().list_channels({})
        invoice_balance = channels["channels"][0]["local_balance"]

        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        time.sleep(10)
        after_channel = self.fiber1.get_client().list_channels({})
        assert int(before_channel["channels"][0]["local_balance"], 16) - int(
            after_channel["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        # Step 3: Shutdown channel and assert on-chain balance
        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        before_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": self.account1["lock_arg"],
                },
                "fee_rate": FeeRate.to_hex(1020),
            }
        )

        tx_hash = self.wait_and_check_tx_pool_fee(FeeRate.DEFAULT, False)
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        after_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        assert after_balance2 - before_balance2 == 200

    def test_tlc_min_value_is_not_zero(self):
        """
        tlc_min_value != 0: amount below min fails route; at or above succeeds.
        Step 1: Open channel with tlc_min_value=2 CKB, wait CHANNEL_READY.
        Step 2: Send amount below min, expect Failed to build route; send 100 CKB, assert balance.
        Step 3: node2 send 2 CKB via invoice, then node2 send 2 CKB - 1; shutdown and assert close output.
        """
        # Step 1: Open channel with tlc_min_value=2 CKB
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
                "tlc_min_value": hex(Amount.ckb(2)),
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )

        # Step 2: Amount below min fails; 100 CKB succeeds
        before_channel = self.fiber1.get_client().list_channels({})
        with pytest.raises(Exception) as exc_info:
            self.send_payment(self.fiber1, self.fiber2, Amount.ckb(2) - 1, True)
        expected_error_message = "Failed to build route"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        self.send_payment(self.fiber1, self.fiber2, Amount.ckb(100), True)
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == Amount.ckb(100)
        )

        # Step 3: node2 send 2 CKB via invoice
        invoice_balance = hex(Amount.ckb(2))
        payment_preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel = self.fiber2.get_client().list_channels({})

        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )

        after_channel = self.fiber2.get_client().list_channels({})
        assert int(before_channel["channels"][0]["local_balance"], 16) - int(
            after_channel["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        # node2 send 2 CKB - 1 (below tlc_min_value for reverse direction)
        channels = self.fiber1.get_client().list_channels({})
        self.send_payment(self.fiber2, self.fiber1, Amount.ckb(2) - 1, True)
        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": self.account1["lock_arg"],
                },
                "fee_rate": FeeRate.to_hex(1020),
            }
        )
        tx_hash = self.wait_and_check_tx_pool_fee(FeeRate.DEFAULT, False)
        tx_response = self.get_tx_message(tx_hash)
        assert (
            Amount.ckb(200) + DEFAULT_MIN_DEPOSIT_CKB
            == tx_response["input_cells"][0]["capacity"]
        )
        assert {
            "args": self.fiber2.get_account()["lock_arg"],
            "capacity": 9600000001 + DEFAULT_MIN_DEPOSIT_CKB,
        } in tx_response["output_cells"]

    def test_tlc_min_value_gt_funding_amount(self):
        """
        tlc_min_value > funding_amount: open channel then send_payment should fail to build route.
        Step 1: Open channel with tlc_min_value 210 CKB > funding 200 CKB, wait CHANNEL_READY.
        Step 2: Try send_payment for full local balance, expect Failed to build route.
        """
        # Step 1: Open channel with tlc_min_value > funding_amount
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
                "tlc_min_value": hex(Amount.ckb(210)),
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        # Step 2: Try send_payment for full local balance, expect Failed to build route
        time.sleep(3)
        self.fiber1.get_client().graph_channels()
        self.fiber1.get_client().graph_nodes()
        payment_preimage = self.generate_random_preimage()
        channels = self.fiber1.get_client().list_channels({})
        invoice_balance = channels["channels"][0]["local_balance"]

        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        expected_error_message = "Failed to build route"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_ckb_tlc_min_value_not_eq_default(self):
        """
        CKB tlc_min_value != default: same as test_tlc_min_value_is_not_zero.
        Step 1: Delegate to test_tlc_min_value_is_not_zero.
        """
        self.test_tlc_min_value_is_not_zero()

    def test_udt_tlc_min_value_not_eq_default(self):
        """
        UDT tlc_min_value != default: open UDT channel with tlc_min_value, pay >= min and < min.
        Step 1: Open UDT channel with tlc_min_value 160 UDT, wait CHANNEL_READY.
        Step 2: Send 160 UDT - 1, expect Failed to build route; send 500 UDT, assert balance.
        Step 3: node2 send 160 UDT then 160 UDT - 16M; shutdown and assert output cells.
        """
        # Step 1: Open UDT channel with tlc_min_value
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
                "tlc_min_value": hex(Amount.udt(160)),
                "funding_udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )

        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        time.sleep(5)
        self.fiber1.get_client().graph_channels()
        self.fiber1.get_client().graph_nodes()
        payment_preimage = self.generate_random_preimage()
        channels = self.fiber1.get_client().list_channels({})

        udt_script = {
            "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
            "hash_type": "type",
            "args": self.udtContract.get_owner_arg_by_lock_arg(
                self.account1["lock_arg"]
            ),
        }
        with pytest.raises(Exception) as exc_info:
            self.send_payment(
                self.fiber1,
                self.fiber2,
                Amount.udt(160) - 1,
                True,
                udt=udt_script,
            )
        expected_error_message = "Failed to build route"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        invoice_balance = hex(Amount.udt(500))

        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert int(before_channel["channels"][0]["local_balance"], 16) - int(
            after_channel["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        # node2 send 160 UDT
        invoice_balance = hex(Amount.udt(160))
        payment_preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        before_channel = self.fiber2.get_client().list_channels({})

        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )

        after_channel = self.fiber2.get_client().list_channels({})
        assert int(before_channel["channels"][0]["local_balance"], 16) - int(
            after_channel["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        # node2 send 160 UDT - 16M
        invoice_balance = hex(Amount.udt(160) - 16_000_000)
        payment_preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        before_channel = self.fiber2.get_client().list_channels({})
        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": self.account1["lock_arg"],
                },
                "fee_rate": FeeRate.to_hex(1020),
            }
        )
        tx_hash = self.wait_and_check_tx_pool_fee(FeeRate.DEFAULT, False)
        tx_response = self.get_tx_message(tx_hash)
        assert {
            "args": self.account2["lock_arg"],
            "capacity": DEFAULT_MIN_DEPOSIT_UDT,
            "udt_args": self.udtContract.get_owner_arg_by_lock_arg(
                self.account1["lock_arg"]
            ),
            "udt_capacity": 18016000000,
        } in tx_response["output_cells"]
