"""
Test cases for open_channel tlc_fee_proportional_millionths parameter.
Covers: default, overflow, custom fee, CKB/UDT, zero, max.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    PaymentFeeRate,
    PaymentStatus,
    TLCFeeRate,
    Timeout,
)


class TestTlcFeeProportionalMillionths(FiberTest):
    """
    Test open_channel tlc_fee_proportional_millionths: default, overflow, custom fee, zero, max; CKB/UDT.
    """

    def test_tlc_fee_proportional_millionths_default(self):
        """
        tlc_fee_proportional_millionths: none (default); open channels, send payment, assert fee and balance.
        Step 1: Start fiber3, connect, open channel fiber1-fiber2 then fiber2-fiber3 (default fee).
        Step 2: Create invoice on fiber3, send payment from fiber1, wait and assert balance change with 0.1% fee.
        """
        # Step 1: Start fiber3, connect, open two channels with default fee
        account3_private_key = self.generate_account(Amount.ckb(1000))
        new_fiber = self.start_new_fiber(account3_private_key)
        time.sleep(3)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(3)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": new_fiber.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        # Step 2: Create invoice, send payment, assert balance (0.1% fee = TLCFeeRate.DEFAULT)
        invoice_balance = hex(Amount.ckb(100))
        payment_preimage = self.generate_random_preimage()
        invoice = new_fiber.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel_12 = self.fiber1.get_client().list_channels({})
        before_channel_32 = new_fiber.get_client().list_channels({})
        time.sleep(10)
        self.fiber2.get_client().graph_channels()
        self.fiber2.get_client().graph_nodes()
        self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        time.sleep(10)
        after_channel_12 = self.fiber1.get_client().list_channels({})
        after_channel_32 = new_fiber.get_client().list_channels({})

        # 0.1% fee => amount + amount * 1000 / 1000000
        expected_debit = int(invoice_balance, 16) + int(
            int(invoice_balance, 16) * TLCFeeRate.DEFAULT / 1_000_000
        )
        assert int(before_channel_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == expected_debit
        assert int(after_channel_32["channels"][0]["local_balance"], 16) - int(
            before_channel_32["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

    def test_tlc_fee_proportional_millionths_overflow(self):
        """
        tlc_fee_proportional_millionths > int.max: open_channel expects Invalid params.
        Step 1: Call open_channel with overflow value, assert error contains Invalid params.
        """
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().open_channel(
                {
                    "peer_id": self.fiber1.get_peer_id(),
                    "funding_amount": hex(Amount.ckb(1000)),
                    "public": True,
                    "tlc_fee_proportional_millionths": "0x1FFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
                }
            )
        expected_error_message = "Invalid params"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_tlc_fee_proportional_millionths_100_100000000_1000_1000(self):
        """
        tlc_fee_proportional_millionths set to very high value; list_channels shows capped value; send 1 CKB.
        Step 1: Open channel with high tlc_fee_proportional_millionths, wait CHANNEL_READY, assert list_channels.
        Step 2: Open fiber3-fiber2 channel with max fee, send payment fiber3->fiber1.
        """
        self.fiber2.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
                "tlc_fee_proportional_millionths": hex(
                    100 * 100000000 * 1000 * 1000
                ),
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(), self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        channel = self.fiber1.get_client().list_channels({})
        assert channel["channels"][0]["tlc_fee_proportional_millionths"] == "0x3e8"
        channel = self.fiber2.get_client().list_channels({})
        assert channel["channels"][0]["tlc_fee_proportional_millionths"] == hex(
            100 * 100000000 * 1000000
        )
        fiber3 = self.start_new_fiber(self.generate_account(Amount.ckb(10000)))
        fiber3.connect_peer(self.fiber2)
        time.sleep(1)
        fiber3.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
                "tlc_fee_proportional_millionths": "0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF",
            }
        )
        self.wait_for_channel_state(
            fiber3.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        self.send_payment(fiber3, self.fiber1, Amount.ckb(1))

    def test_ckb_tlc_fee_proportional_millionths_not_eq_default(self):
        """
        tlc_fee_proportional_millionths != default: node1->node3 fee 1M, node3->node1 fee 1000.
        Step 1: Build topology fiber1-fiber2 (default fee), fiber2-fiber3 (fiber2_tlc_fee=1000000).
        Step 2: fiber1 send payment to fiber3, assert balance change includes 1% fee; fiber3 send to fiber1, assert 0.1% fee.
        """
        # Step 1: Build topology
        account3_private_key = self.generate_account(Amount.ckb(1000))
        new_fiber = self.start_new_fiber(account3_private_key)
        time.sleep(3)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(3)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(3)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        fiber2_tlc_fee = 1000000
        self.fiber2.get_client().open_channel(
            {
                "peer_id": new_fiber.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
                "tlc_fee_proportional_millionths": hex(fiber2_tlc_fee),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        invoice_balance = hex(Amount.ckb(100))
        payment_preimage = self.generate_random_preimage()
        invoice = new_fiber.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel_12 = self.fiber1.get_client().list_channels({})
        before_channel_32 = new_fiber.get_client().list_channels({})
        time.sleep(1)
        self.fiber2.get_client().graph_channels()
        self.fiber2.get_client().graph_nodes()
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_rate": hex(PaymentFeeRate.MAX),
            }
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel_12 = self.fiber1.get_client().list_channels({})
        after_channel_32 = new_fiber.get_client().list_channels({})

        expected_debit = int(invoice_balance, 16) + int(
            int(invoice_balance, 16) * fiber2_tlc_fee / 1_000_000
        )
        assert int(before_channel_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == expected_debit
        assert int(after_channel_32["channels"][0]["local_balance"], 16) - int(
            before_channel_32["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        invoice_balance = hex(Amount.ckb(1))
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        time.sleep(1)
        payment = new_fiber.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_rate": hex(PaymentFeeRate.MAX),
            }
        )
        self.wait_payment_state(
            new_fiber, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel_2_12 = self.fiber1.get_client().list_channels({})
        after_channel_2_32 = new_fiber.get_client().list_channels({})
        new_fiber.get_client().graph_nodes()
        # 0.1% fee on reverse path (TLCFeeRate.DEFAULT = 1000)
        expected_reverse_debit = int(invoice_balance, 16) + int(
            int(invoice_balance, 16) * TLCFeeRate.DEFAULT / 1_000_000
        )
        assert (
            int(after_channel_32["channels"][0]["local_balance"], 16)
            - int(after_channel_2_32["channels"][0]["local_balance"], 16)
            == expected_reverse_debit
        )
        assert int(after_channel_2_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

    def test_normal_fee(self):
        """
        Topology 1-2-3: fiber1->fiber3 fee 1%, fiber3->fiber1 fee 0.1%; assert fee and balances.
        Step 1: Start fiber3, open channel 1-2 (fee 0.1%) and 2-3 (fiber2 fee 1%).
        Step 2: Send 10 CKB fiber1->fiber3, assert fee = 10 CKB * 1%; send 1 CKB fiber3->fiber1, assert fee = 0.1%.
        Step 3: Assert final channel balances.
        """
        # Step 1: Build topology 1-2-3 with different fees
        self.start_new_fiber(self.generate_account(Amount.ckb(1000)))
        self.open_channel(
            self.fibers[0],
            self.fibers[1],
            Amount.ckb(1000),
            Amount.ckb(1),
            fiber1_fee=TLCFeeRate.DEFAULT,
            fiber2_fee=TLCFeeRate.DEFAULT,
        )
        self.open_channel(
            self.fibers[1],
            self.fibers[2],
            Amount.ckb(1000),
            Amount.ckb(1),
            fiber1_fee=1000000,
            fiber2_fee=TLCFeeRate.DEFAULT,
        )
        time.sleep(5)
        # Step 2: Send 10 CKB fiber1->fiber3, assert fee 1%
        payment_hash = self.send_payment(
            self.fibers[0], self.fibers[2], Amount.ckb(10)
        )
        payment = self.fibers[0].get_client().get_payment(
            {"payment_hash": payment_hash}
        )
        assert payment["fee"] == hex(
            int(Amount.ckb(10) * 1000000 / 1_000_000)
        )
        # Send 1 CKB fiber3->fiber1, assert fee 0.1%
        payment_hash = self.send_payment(
            self.fibers[2], self.fibers[0], Amount.ckb(1)
        )
        payment = self.fibers[2].get_client().get_payment(
            {"payment_hash": payment_hash}
        )
        assert payment["fee"] == hex(
            int(Amount.ckb(1) * TLCFeeRate.DEFAULT / 1_000_000)
        )
        # Step 3: Assert final channel balances
        channels1 = self.fiber1.get_client().list_channels({})
        channels2 = self.fibers[2].get_client().list_channels({})
        assert channels1["channels"][0]["local_balance"] == hex(98100000000)
        assert channels2["channels"][0]["local_balance"] == hex(899900001)

    # def test_fee_mutil(self):
    #     self.start_new_fiber(self.generate_account(10000))
    #     self.start_new_fiber(self.generate_account(10000))
    #
    #     self.open_channel(self.fibers[0], self.fibers[1], 1000 * 100000000, 1, fiber1_fee=1000, fiber2_fee=1000)
    #     self.open_channel(self.fibers[1], self.fibers[2], 1000 * 100000000, 1, fiber1_fee=1000000, fiber2_fee=1000)
    #     self.open_channel(self.fibers[2], self.fibers[3], 1000 * 100000000, 1, fiber1_fee=2000000, fiber2_fee=1000)
    #     self.open_channel(self.fibers[3], self.fibers[0], 1000 * 100000000, 1, fiber1_fee=3000000, fiber2_fee=1000)
    #     for i in range(100):
    #         self.send_payment(self.fibers[0], self.fibers[0], 1 * 100000000)
    #     # (100000000 * (1+ 3000000/ 1000000) )   * (1+ 2000000/ 1000000)

    def test_tlc_fee_proportional_millionths_max(self):
        """
        tlc_fee_proportional_millionths at max (340282366); assert fee and reverse payment.
        Step 1: Open fiber1-fiber2 then fiber2-fiber3 with fiber2_tlc_fee=340282366, wait CHANNEL_READY.
        Step 2: Send payment fiber1->fiber3, assert balance; send reverse with max_fee_amount.
        Step 3: Assert reverse path balance change (0.1% fee).
        """
        account3_private_key = self.generate_account(Amount.ckb(1000))
        new_fiber = self.start_new_fiber(account3_private_key)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(3)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(20000)),
                "public": True,
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        fiber2_tlc_fee = 340282366
        self.fiber2.get_client().open_channel(
            {
                "peer_id": new_fiber.get_peer_id(),
                "funding_amount": hex(Amount.ckb(10000)),
                "public": True,
                "tlc_fee_proportional_millionths": hex(fiber2_tlc_fee),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        invoice_balance = hex(Amount.ckb(1))
        payment_preimage = self.generate_random_preimage()
        invoice = new_fiber.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel_12 = self.fiber1.get_client().list_channels({})
        before_channel_32 = new_fiber.get_client().list_channels({})
        time.sleep(10)
        self.fiber2.get_client().graph_channels()
        self.fiber2.get_client().graph_nodes()
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_rate": hex(PaymentFeeRate.MAX),
            }
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel_12 = self.fiber1.get_client().list_channels({})
        after_channel_32 = new_fiber.get_client().list_channels({})

        expected_debit = int(invoice_balance, 16) + int(
            int(invoice_balance, 16) * fiber2_tlc_fee / 1_000_000
        )
        assert int(before_channel_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == expected_debit
        assert int(after_channel_32["channels"][0]["local_balance"], 16) - int(
            before_channel_32["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        invoice_balance = hex(Amount.ckb(1))
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        time.sleep(1)
        payment = new_fiber.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_amount": hex(Amount.ckb(1000)),
            }
        )
        self.wait_payment_state(
            new_fiber, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel_2_12 = self.fiber1.get_client().list_channels({})
        after_channel_2_32 = new_fiber.get_client().list_channels({})
        new_fiber.get_client().graph_nodes()
        expected_reverse = int(invoice_balance, 16) + int(
            int(invoice_balance, 16) * TLCFeeRate.DEFAULT / 1_000_000
        )
        assert (
            int(after_channel_32["channels"][0]["local_balance"], 16)
            - int(after_channel_2_32["channels"][0]["local_balance"], 16)
            == expected_reverse
        )
        assert int(after_channel_2_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

    def test_udt_tlc_fee_proportional_millionths_not_eq_default(self):
        """
        UDT tlc_fee_proportional_millionths != default: UDT channel with custom fee, assert fee and balance.
        Step 1: Setup UDT, open fiber1-fiber2 and fiber2-fiber3 with fiber2_tlc_fee=1000000.
        Step 2: Send UDT payment fiber1->fiber3, assert balance; reverse payment, assert balance.
        """
        account3_private_key = self.generate_account(
            Amount.ckb(1000), self.Config.ACCOUNT_PRIVATE_1, Amount.ckb(1000)
        )
        new_fiber = self.start_new_fiber(account3_private_key)
        time.sleep(3)
        self.fiber2.connect_peer(new_fiber)
        self.faucet(
            self.fiber2.account_private,
            0,
            self.fiber1.account_private,
            Amount.ckb(1000),
        )
        self.faucet(
            self.fiber1.account_private,
            0,
            self.fiber1.account_private,
            Amount.ckb(1000),
        )
        account1_cells = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        account2_cells = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )
        print("account1:", account1_cells)
        print("account2:", account2_cells)
        tx_hash = self.Ckb_cli.wallet_transfer_by_private_key(
            self.Config.ACCOUNT_PRIVATE_2,
            self.account1["address"]["testnet"],
            10000,
            self.node.rpcUrl,
        )
        self.Miner.miner_until_tx_committed(self.node, tx_hash)

        time.sleep(3)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
                "tlc_fee_proportional_millionths": hex(1000000),
                "funding_udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        fiber2_tlc_fee = 1000000
        self.fiber2.get_client().open_channel(
            {
                "peer_id": new_fiber.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
                "tlc_fee_proportional_millionths": hex(fiber2_tlc_fee),
                "funding_udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        invoice_balance = hex(Amount.ckb(100))
        payment_preimage = self.generate_random_preimage()
        invoice = new_fiber.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        before_channel_12 = self.fiber1.get_client().list_channels({})
        before_channel_32 = new_fiber.get_client().list_channels({})
        time.sleep(10)
        self.fiber2.get_client().graph_channels()
        self.fiber2.get_client().graph_nodes()
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_rate": hex(PaymentFeeRate.MAX),
            }
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"],
            PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS,
        )
        after_channel_12 = self.fiber1.get_client().list_channels({})
        after_channel_32 = new_fiber.get_client().list_channels({})

        expected_debit_udt = int(invoice_balance, 16) + int(
            int(invoice_balance, 16) * fiber2_tlc_fee / 1_000_000
        )
        assert int(before_channel_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == expected_debit_udt
        assert int(after_channel_32["channels"][0]["local_balance"], 16) - int(
            before_channel_32["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)
        invoice_balance = hex(Amount.ckb(1))
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": {
                    "code_hash": self.udtContract.get_code_hash(True, self.node.rpcUrl),
                    "hash_type": "type",
                    "args": self.udtContract.get_owner_arg_by_lock_arg(
                        self.account1["lock_arg"]
                    ),
                },
            }
        )
        time.sleep(1)
        payment = new_fiber.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_amount": hex(Amount.ckb(1000)),
            }
        )
        time.sleep(5)
        new_fiber.get_client().get_payment({"payment_hash": payment["payment_hash"]})
        after_channel_2_12 = self.fiber1.get_client().list_channels({})
        after_channel_2_32 = new_fiber.get_client().list_channels({})
        new_fiber.get_client().graph_nodes()
        expected_reverse_udt = int(invoice_balance, 16) + int(
            int(invoice_balance, 16) * TLCFeeRate.DEFAULT / 1_000_000
        )
        assert (
            int(after_channel_32["channels"][0]["local_balance"], 16)
            - int(after_channel_2_32["channels"][0]["local_balance"], 16)
            == expected_reverse_udt
        )
        assert int(after_channel_2_12["channels"][0]["local_balance"], 16) - int(
            after_channel_12["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

    def test_ckb_tlc_fee_proportional_millionths_is_zero(self):
        """
        tlc_fee_proportional_millionths == 0: fiber2-fiber3 channel has zero fee; payment fee is 0.
        Step 1: Open fiber1-fiber2 (default) and fiber2-fiber3 (fee 0), wait CHANNEL_READY.
        Step 2: Send payment fiber1->fiber3, assert payment fee is 0x0.
        """
        account3_private_key = self.generate_account(Amount.ckb(1000))
        new_fiber = self.start_new_fiber(account3_private_key)
        self.fiber2.connect_peer(new_fiber)
        time.sleep(1)
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(500)),
                "public": True,
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        fiber2_tlc_fee = TLCFeeRate.ZERO
        self.fiber2.get_client().open_channel(
            {
                "peer_id": new_fiber.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
                "tlc_fee_proportional_millionths": hex(fiber2_tlc_fee),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber2.get_client(), new_fiber.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY,
        )
        payment_hash = self.send_payment(
            self.fiber1, new_fiber, Amount.ckb(100)
        )
        payment = self.fiber1.get_client().get_payment(
            {"payment_hash": payment_hash}
        )
        assert payment["fee"] == "0x0"
