"""
Test open_channel max_tlc_number_in_flight: boundary values and payment behavior when zero.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.config import DEFAULT_MIN_DEPOSIT_CKB
from framework.constants import Amount, ChannelState, Currency, HashAlgorithm, PaymentStatus, Timeout


class TestMaxTlcNumberInFlight(FiberTest):
    """
    Test open_channel max_tlc_number_in_flight: reject when greater than system max (253);
    when zero, channel opens but payment fails; then shutdown and assert balance.
    """

    def test_max_tlc_number_in_flight_very_big(self):
        """
        open_channel with max_tlc_number_in_flight greater than system max (253) should be rejected.
        Step 1: Call open_channel with max_tlc_number_in_flight 0xffffffffff.
        Step 2: Assert error message contains "greater than the system maximal value 253".
        """
        # Step 1: Call open_channel with very large max_tlc_number_in_flight
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().open_channel(
                {
                    "peer_id": self.fiber2.get_peer_id(),
                    "funding_amount": hex(Amount.ckb(200)),
                    "public": True,
                    "max_tlc_number_in_flight": "0xffffffffff",
                }
            )
        # Step 2: Assert error message
        expected_error_message = "greater than the system maximal value 253"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    # @pytest.mark.skip("https://github.com/nervosnetwork/fiber/issues/450")
    def test_max_tlc_number_in_flight_zero(self):
        """
        When max_tlc_number_in_flight is 0: channel opens, payment fails, shutdown and assert balance.
        Step 1: Open channel with max_tlc_number_in_flight 0, wait CHANNEL_READY.
        Step 2: Create invoice and send payment; wait payment Failed.
        Step 3: Shutdown channel; assert CKB balance equals DEFAULT_MIN_DEPOSIT_CKB.
        """
        # Step 1: Open channel with max_tlc_number_in_flight 0
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
                "max_tlc_number_in_flight": "0x0",
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        time.sleep(5)

        # Step 2: Send payment; expect Failed
        self.fiber1.get_client().graph_channels()
        self.fiber1.get_client().graph_nodes()
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(100)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.FAILED
        )
        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        # Step 3: Shutdown channel; assert balance
        before_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": {
                    "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
                    "hash_type": "type",
                    "args": self.account1["lock_arg"],
                },
                "fee_rate": hex(1020),  # 0x3FC
            }
        )

        tx_hash = self.wait_and_check_tx_pool_fee(1000, False)
        self.Miner.miner_until_tx_committed(self.node, tx_hash)
        after_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        assert (after_balance2 - before_balance2) * Amount.CKB == DEFAULT_MIN_DEPOSIT_CKB
