from framework.basic_fiber import FiberTest


class TestNewInvoice(FiberTest):

    def test_new_invoice(self):
        """
        node_info -
        new_invoice allow_trampoline_routing = None
        new_invoice (allow_trampoline_routing:False)-> attrs 不包含{"feature": ["TRAMPOLINE_ROUTING_OPTIONAL"]}
        new_invoice (allow_trampoline_routing:True)-> attrs 包含{"feature": ["TRAMPOLINE_ROUTING_OPTIONAL"]}
        Returns:
        """
        node_info = self.fiber1.get_client().node_info()
        allow_trampoline_routing_none_invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
            }
        )
        allow_trampoline_routing_false_invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
                "allow_trampoline_routing": False,
            }
        )
        allow_trampoline_routing_true_invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
                "allow_trampoline_routing": True,
            }
        )
        print("node info:", node_info)
        assert "TRAMPOLINE_ROUTING_REQUIRED" in node_info["features"]
        print(
            "new invoice allow_trampoline_routing_none_invoice:",
            allow_trampoline_routing_none_invoice,
        )
        assert "TRAMPOLINE_ROUTING_OPTIONAL" not in str(
            allow_trampoline_routing_none_invoice["invoice"]["data"]["attrs"]
        )
        print(
            "new invoice allow_trampoline_routing_false_invoice:",
            allow_trampoline_routing_false_invoice,
        )
        assert "TRAMPOLINE_ROUTING_OPTIONAL" not in str(
            allow_trampoline_routing_false_invoice["invoice"]["data"]["attrs"]
        )
        print(
            "new invoice allow_trampoline_routing_true_invoice:",
            allow_trampoline_routing_true_invoice,
        )
        assert "TRAMPOLINE_ROUTING_OPTIONAL" in str(
            allow_trampoline_routing_true_invoice["invoice"]["data"]["attrs"]
        )
