import time

import pytest

from framework.basic_fiber import FiberTest


class TestMpp(FiberTest):

    def test_mpp_with_oneway(self):
        """
        节点到trampoline 走mpp
            - todo 报错

        Returns:
        """
        # self
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.fiber4 = self.start_new_fiber(self.generate_account(10000))

        self.open_channel(
            self.fiber1,
            self.fiber2,
            1000 * 100000000,
            0,
            other_config={
                "public": False,
                "one_way": True,
            },
        )
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 0)

        self.open_channel(
            self.fiber2,
            self.fiber3,
            1000 * 100000000,
            0,
            other_config={
                "public": False,
            },
        )
        self.open_channel(self.fiber2, self.fiber4, 1000 * 100000000, 0)
        self.open_channel(self.fiber2, self.fiber3, 1000 * 100000000, 0)
        self.open_channel(self.fiber3, self.fiber4, 1000 * 100000000, 0)
        self.open_channel(self.fiber1, self.fiber4, 5000 * 100000000, 0)

        before_balance = self.get_fibers_balance()

        invoice = self.fiber4.get_client().new_invoice(
            {
                "amount": hex(1500 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                # "payment_preimage": self.generate_random_preimage(),
                "payment_hash": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
                "allow_mpp": True,
                "allow_trampoline_routing": True,
            }
        )
        with pytest.raises(Exception) as exc_info:
            payment = self.fiber1.get_client().send_payment(
                {
                    "invoice": invoice["invoice_address"],
                    "trampoline_hops": [
                        self.fiber2.get_client().node_info()["node_id"],
                    ],
                }
            )
        expected_error_message = "no path found"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_mpp_with_oneway_ckb_hash(self):
        """
        Returns:
        """
        # self
        # self.fiber3 = self.start_new_mock_fiber("")
        # self.fiber4 = self.start_new_mock_fiber("")

        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.fiber4 = self.start_new_fiber(self.generate_account(10000))

        self.open_channel(
            self.fiber1,
            self.fiber2,
            3000 * 100000000,
            0,
            other_config={
                # "public": False,
                # "one_way": True,
            },
        )

        self.open_channel(
            self.fiber2,
            self.fiber3,
            1000 * 100000000,
            0,
            other_config={
                # "public": False,
            },
        )
        self.open_channel(self.fiber2, self.fiber4, 1000 * 100000000, 0)
        self.open_channel(self.fiber2, self.fiber3, 1000 * 100000000, 0)
        self.open_channel(self.fiber3, self.fiber4, 1000 * 100000000, 0)
        self.open_channel(self.fiber1, self.fiber4, 5000 * 100000000, 0)

        invoice = self.fiber4.get_client().new_invoice(
            {
                "amount": hex(1001 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "ckb_hash",
                "allow_mpp": True,
                "allow_trampoline_routing": True,
            }
        )
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_amount": hex(100000000000),
                "trampoline_hops": [
                    self.fiber2.get_client().node_info()["node_id"],
                ],
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], "Success")

    def test_mpp_with_oneway_hash_algorithm_sha256(self):
        """
        Returns:
        """

        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.fiber4 = self.start_new_fiber(self.generate_account(10000))

        self.open_channel(
            self.fiber1,
            self.fiber2,
            3000 * 100000000,
            0,
            other_config={
                "public": False,
                "one_way": True,
            },
        )

        self.open_channel(
            self.fiber2,
            self.fiber3,
            1000 * 100000000,
            0,
            other_config={
                "public": False,
            },
        )
        self.open_channel(self.fiber2, self.fiber4, 1000 * 100000000, 0)
        self.open_channel(self.fiber2, self.fiber3, 1000 * 100000000, 0)
        self.open_channel(self.fiber3, self.fiber4, 1000 * 100000000, 0)
        self.open_channel(self.fiber1, self.fiber4, 5000 * 100000000, 0)

        invoice = self.fiber4.get_client().new_invoice(
            {
                "amount": hex(1001 * 100000000),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
                "allow_mpp": True,
                "allow_trampoline_routing": True,
            }
        )
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
                "max_fee_amount": hex(100000000000),
                "trampoline_hops": [
                    self.fiber2.get_client().node_info()["node_id"],
                ],
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], "Success")
