"""
Test cases for new_invoice udt_type_script: non-existent whitelist type script can be used and parse_invoice succeeds.
"""
import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Currency, HashAlgorithm


class TestUdtTypeScript(FiberTest):
    """
    Test new_invoice udt_type_script: not in whitelist (not_exist) can still create invoice and parse_invoice returns.
    """

    @pytest.mark.skip("repeat")
    def test_white_type_script(self):
        """Placeholder for whitelist type script test."""
        pass

    def test_not_exist_white_type_script(self):
        """
        Create invoice with udt_type_script not in whitelist; parse_invoice should succeed.
        Step 1: Create invoice with random udt_type_script (code_hash, hash_type, args).
        Step 2: Parse invoice and assert no exception.
        """
        # Step 1: Create invoice with non-whitelist udt_type_script
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(100)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
                "udt_type_script": {
                    "code_hash": self.generate_random_str(64),
                    "hash_type": "data2",
                    "args": "0x12",
                },
            }
        )

        # Step 2: Parse invoice and assert no exception
        parsed = self.fiber1.get_client().parse_invoice(
            {"invoice": invoice["invoice_address"]}
        )
        assert parsed is not None

    @pytest.mark.skip("repeat")
    def test_none(self):
        """Placeholder for none udt_type_script test."""
        pass
