"""
Test cases for new_invoice expiry parameter: 0x0, overflow, and normal expiry.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    HashAlgorithm,
    InvoiceStatus,
    PaymentStatus,
    Timeout,
)


class TestExpiry(FiberTest):
    """
    Test new_invoice expiry: 0x0 (expired immediately), overflow (Invalid params), normal expiry then pay.
    """

    def test_0x(self):
        """
        Expiry 0x0: invoice becomes Expired; send_payment should fail with "invoice is expired".
        Then create invoice with normal expiry and complete payment.
        Step 1: Open channel and wait CHANNEL_READY.
        Step 2: Create invoice with expiry 0x0; wait invoice Expired; send_payment expects "invoice is expired".
        Step 3: Create new invoice with normal expiry; send payment and wait success; assert balance.
        """
        # Step 1: Open channel and wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice with expiry 0x0; wait Expired; send_payment expects "invoice is expired"
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0x0",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        self.wait_invoice_state(
            self.fiber1,
            invoice["invoice"]["data"]["payment_hash"],
            InvoiceStatus.EXPIRED,
            timeout=1,
        )
        time.sleep(Timeout.POLL_INTERVAL)
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        expected_error_message = "invoice is expired"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 3: Create new invoice with normal expiry; send payment and wait success; assert balance
        amount = 1
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(amount),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel = self.fiber1.get_client().list_channels({})
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS
        )
        self.wait_invoice_state(
            self.fiber2, payment["payment_hash"], InvoiceStatus.PAID,
            timeout=Timeout.CHANNEL_READY
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            == int(after_channel["channels"][0]["local_balance"], 16) + amount
        )

    def test_invoice_expiry(self):
        """
        Invoice with short expiry (0x1) should become Expired after wait.
        Step 1: Create invoice with expiry 0x1.
        Step 2: Wait for invoice state Expired.
        """
        # Step 1: Create invoice with expiry 0x1
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0x1",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        # Step 2: Wait for invoice state Expired
        self.wait_invoice_state(
            self.fiber2,
            invoice["invoice"]["data"]["payment_hash"],
            InvoiceStatus.EXPIRED,
            timeout=10,
        )

    @pytest.mark.skip("unstable")
    def test_0x1(self):
        """
        (Skipped: unstable) Expiry 0x1: pay within 0.95s may fail.
        Step 1: Open channel and wait CHANNEL_READY.
        Step 2: Create invoice with expiry 0x1; wait 0.95s; send payment; expect Failed.
        """
        # Step 1: Open channel and wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        # Step 2: Create invoice with expiry 0x1; wait 0.95s; send payment; expect Failed
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0x1",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        time.sleep(0.95)
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.FAILED,
            timeout=Timeout.CHANNEL_READY
        )

    def test_overflow(self):
        """
        new_invoice with overflow expiry should raise with "Invalid params".
        Step 1: Call new_invoice with very large expiry; expect exception containing "Invalid params".
        """
        # Step 1: Call new_invoice with overflow expiry; expect "Invalid params"
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xffffffffffffffffff",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )
        expected_error_message = "Invalid params"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
