"""
Test cases for new_invoice currency parameter: Fibb/Fibt rejected, Fibd accepted.
"""
import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Currency, HashAlgorithm


class TestCurrency(FiberTest):
    """
    Test new_invoice currency: Fibb and Fibt should be rejected with "Currency must be Fibd with the chain network";
    Fibd should be accepted and invoice currency field is Fibd.
    """

    def test_fibb_fibt_fibd(self):
        """
        Fibb and Fibt should raise with "Currency must be Fibd with the chain network";
        Fibd should succeed and invoice currency is Fibd.
        Step 1: Call new_invoice with currency Fibb; expect exception with expected message.
        Step 2: Call new_invoice with currency Fibt; expect exception with expected message.
        Step 3: Call new_invoice with currency Fibd; assert invoice currency is Fibd.
        """
        # Step 1: Call new_invoice with currency Fibb; expect exception with expected message
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": "Fibb",
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )
        expected_error_message = "Currency must be Fibd with the chain network"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 2: Call new_invoice with currency Fibt; expect exception with expected message
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": "Fibt",
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )
        expected_error_message = "Currency must be Fibd with the chain network"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 3: Call new_invoice with currency Fibd; assert invoice currency is Fibd
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        assert invoice["invoice"]["currency"] == Currency.FIBD
