import time

import pytest

from framework.basic_fiber import FiberTest


class TestInvoiceStatus(FiberTest):
    """
    Open - The invoice is open and can be paid.
    Cancelled - The invoice is cancelled.
    Expired - The invoice is expired.
    Received - The invoice is received, but not settled yet.
    Paid - The invoice is paid.

    """

    def test_Expired(self):
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.open_channel(self.fiber3, self.fiber1, 1000 * 100000000, 1000 * 100000000)
        self.open_channel(self.fiber1, self.fiber2, 1000 * 100000000, 1000 * 100000000)
        preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0x0",
                "final_cltv": "0x28",
                "payment_preimage": preimage,
                "hash_algorithm": "sha256",
            }
        )
        result = self.fiber1.get_client().get_invoice(
            {
                "payment_hash": invoice["invoice"]["data"]["payment_hash"],
            }
        )
        assert result["status"] == "Expired"
        with pytest.raises(Exception) as exc_info:
            payment = self.fiber2.get_client().send_payment(
                {
                    "invoice": invoice["invoice_address"],
                }
            )
        expected_error_message = "invoice is expired"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        #         Paid - The invoice is paid.
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xffff",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
            }
        )
        payment = self.fiber2.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(self.fiber2, payment["payment_hash"])
        payment = self.fiber3.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(self.fiber3, payment["payment_hash"], "Failed")

        # Cancelled
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xffff",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
            }
        )
        self.fiber1.get_client().cancel_invoice(
            {
                "payment_hash": invoice["invoice"]["data"]["payment_hash"],
            }
        )
        self.fiber2.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        time.sleep(3)
        # cost invoice same time
        for i in range(10):
            invoice = self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": "Fibd",
                    "description": "test invoice generated by node2",
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": "sha256",
                }
            )
            payment2 = self.fiber2.get_client().send_payment(
                {
                    "invoice": invoice["invoice_address"],
                }
            )
            payment3 = self.fiber3.get_client().send_payment(
                {
                    "invoice": invoice["invoice_address"],
                }
            )
            self.wait_payment_finished(self.fiber2, payment2["payment_hash"])
            self.wait_payment_finished(self.fiber3, payment3["payment_hash"])
            payment2 = self.fiber2.get_client().get_payment(
                {"payment_hash": payment2["payment_hash"]}
            )
            payment3 = self.fiber3.get_client().get_payment(
                {"payment_hash": payment3["payment_hash"]}
            )
            # todo 目前会有双花
            assert payment2["status"] != payment3["status"]
