import pytest

from framework.basic_fiber import FiberTest


class TestPaymentPreimage(FiberTest):
    """
    - Hash256
    - 重复的 payment_preimage
    """

    def test_duplicate_payment_preimag(self):
        """
        1. new invoice
        2. new invoice again
        Returns:
        """
        preimage = self.generate_random_preimage()
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(100),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": preimage,
                "hash_algorithm": "sha256",
            }
        )
        with pytest.raises(Exception) as exc_info:
            invoice = self.fiber2.get_client().new_invoice(
                {
                    "amount": hex(120),
                    "currency": "Fibd",
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": preimage,
                    "hash_algorithm": "sha256",
                }
            )
        expected_error_message = "invoice already exists"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
