"""
Test cases for new_invoice amount parameter: zero, overflow, normal, amount > local balance.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    HashAlgorithm,
    InvoiceStatus,
    PaymentStatus,
    Timeout,
)


class TestAmount(FiberTest):
    """
    Test new_invoice amount: zero, overflow, normal value, amount greater than local balance.
    """

    def test_amount_is_zero_or_gt_local_amount(self):
        """
        Invoice amount 0 should reject send_payment with "amount must be greater than 0";
        amount > local_balance should reject with "no path found"; amount == local_balance should succeed.
        Step 1: Open channel and wait CHANNEL_READY.
        Step 2: Create invoice with amount 0; send_payment expects "amount must be greater than 0".
        Step 3: Create invoice with amount > local_balance; send_payment expects "no path found".
        Step 4: Create invoice with amount == local_balance; send payment and wait success; assert local_balance is 0.
        """
        # Step 1: Open channel and wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice with amount 0; send_payment expects "amount must be greater than 0"
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(0),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        expected_error_message = "amount must be greater than 0"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 3: Create invoice with amount > local_balance; send_payment expects "no path found"
        channels = self.fiber1.get_client().list_channels({})
        amount_over = int(channels["channels"][0]["local_balance"], 16) + 1
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(amount_over),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        expected_error_message = "no path found"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 4: Create invoice with amount == local_balance; send payment and wait success; assert local_balance is 0
        amount_exact = int(channels["channels"][0]["local_balance"], 16)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(amount_exact),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS
        )
        channels = self.fiber1.get_client().list_channels({})
        assert int(channels["channels"][0]["local_balance"], 16) == 0

    def test_amount_is_over_flow(self):
        """
        new_invoice with overflow amount should raise with "Invalid params".
        Step 1: Call new_invoice with very large amount; expect exception containing "Invalid params".
        """
        # Step 1: Call new_invoice with very large amount; expect exception containing "Invalid params"
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().new_invoice(
                {
                    "amount": "0xffffffffffffffffffffffffffffffffffffffffff",
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )
        expected_error_message = "Invalid params"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_amount_is_normal(self):
        """
        Normal amount: open channel, create invoice with normal amount, send payment, verify success and balance.
        Step 1: Open channel and wait CHANNEL_READY.
        Step 2: Create invoice with normal amount (1 shannon).
        Step 3: List channels before payment.
        Step 4: Send payment using invoice.
        Step 5: Wait for payment success and invoice paid.
        Step 6: List channels after payment; assert local_balance decreased by amount.
        """
        # Step 1: Open channel and wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice with normal amount (1 shannon)
        amount = 1
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(amount),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)

        # Step 3: List channels before payment
        before_channel = self.fiber1.get_client().list_channels({})

        # Step 4: Send payment using invoice
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )

        # Step 5: Wait for payment success and invoice paid
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS
        )
        self.wait_invoice_state(
            self.fiber2, payment["payment_hash"], InvoiceStatus.PAID,
            timeout=Timeout.CHANNEL_READY
        )

        # Step 6: List channels after payment; assert local_balance decreased by amount
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            == int(after_channel["channels"][0]["local_balance"], 16) + amount
        )
