"""
Test cases for new_invoice final_expiry_delta: min 9600000, max 1209600000.
"""
import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Currency, HashAlgorithm


# final_expiry_delta bounds (milliseconds)
FINAL_EXPIRY_DELTA_MIN = 9600000
FINAL_EXPIRY_DELTA_MAX = 1209600000


class TestFinalExpiryDelta(FiberTest):
    """
    Test new_invoice final_expiry_delta: below min or above max should reject; min/max should accept and appear in attrs.
    """

    def test_final_expiry_delta_check(self):
        """
        final_expiry_delta below 9600000 or above 1209600000 should be rejected; 9600000 and 1209600000 should succeed.
        Step 1: Call new_invoice with final_expiry_delta 9600000-1; expect error.
        Step 2: Call new_invoice with final_expiry_delta 9600000; assert attrs final_htlc_minimum_expiry_delta.
        Step 3: Call new_invoice with final_expiry_delta 1209600000+1; expect error.
        Step 4: Call new_invoice with final_expiry_delta 1209600000; assert attrs.
        """
        # Step 1: final_expiry_delta below min should be rejected
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xff",
                    "final_expiry_delta": hex(FINAL_EXPIRY_DELTA_MIN - 1),
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )
        expected_error_message = (
            "final_expiry_delta must be greater than or equal to 9600000"
        )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 2: final_expiry_delta 9600000 should succeed and appear in attrs
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xff",
                "final_expiry_delta": hex(FINAL_EXPIRY_DELTA_MIN),
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        assert invoice["invoice"]["data"]["attrs"][2][
            "final_htlc_minimum_expiry_delta"
        ] == hex(FINAL_EXPIRY_DELTA_MIN)

        # Step 3: final_expiry_delta above max should be rejected
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xff",
                    "final_expiry_delta": hex(FINAL_EXPIRY_DELTA_MAX + 1),
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )
        expected_error_message = (
            "final_expiry_delta must be less than or equal to 1209600000"
        )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 4: final_expiry_delta 1209600000 should succeed and appear in attrs
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xff",
                "final_expiry_delta": hex(FINAL_EXPIRY_DELTA_MAX),
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        assert invoice["invoice"]["data"]["attrs"][2][
            "final_htlc_minimum_expiry_delta"
        ] == hex(FINAL_EXPIRY_DELTA_MAX)
