"""
Test cases for new_invoice payment_preimage: duplicate preimage should reject with "invoice already exists".
"""
import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Currency, HashAlgorithm


class TestPaymentPreimage(FiberTest):
    """
    Test new_invoice payment_preimage: Hash256 format; duplicate preimage should raise "invoice already exists".
    """

    def test_duplicate_payment_preimag(self):
        """
        Duplicate payment_preimage: first new_invoice succeeds; second new_invoice with same preimage should raise "invoice already exists".
        Step 1: Create first invoice with given preimage.
        Step 2: Create second invoice with same preimage and different amount; expect exception "invoice already exists".
        """
        # Step 1: Create first invoice with given preimage
        preimage = self.generate_random_preimage()
        self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(100)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )

        # Step 2: Create second invoice with same preimage; expect "invoice already exists"
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().new_invoice(
                {
                    "amount": hex(Amount.ckb(120)),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": preimage,
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )
        expected_error_message = "invoice already exists"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
