import pytest

from framework.basic_fiber import FiberTest


class TestFinalExpiryDelta(FiberTest):

    def test_final_expiry_delta_check(self):
        with pytest.raises(Exception) as exc_info:
            invoice = self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": "Fibd",
                    "description": "test invoice generated by node2",
                    "expiry": "0xff",
                    "final_expiry_delta": hex(9600000 - 1),
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": "sha256",
                }
            )
        expected_error_message = (
            "final_expiry_delta must be greater than or equal to 9600000"
        )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xff",
                "final_expiry_delta": hex(9600000),
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
            }
        )
        assert invoice["invoice"]["data"]["attrs"][2][
            "final_htlc_minimum_expiry_delta"
        ] == hex(9600000)
        with pytest.raises(Exception) as exc_info:
            invoice = self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": "Fibd",
                    "description": "test invoice generated by node2",
                    "expiry": "0xff",
                    "final_expiry_delta": hex(1209600000 + 1),
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": "sha256",
                }
            )
        expected_error_message = (
            "final_expiry_delta must be less than or equal to 1209600000"
        )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xff",
                "final_expiry_delta": hex(1209600000),
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
            }
        )
        assert invoice["invoice"]["data"]["attrs"][2][
            "final_htlc_minimum_expiry_delta"
        ] == hex(1209600000)
