"""
Test cases for new_invoice hash_algorithm: none (default sha256), sha256, ckb_hash, invalid.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    HashAlgorithm,
    InvoiceStatus,
    PaymentStatus,
    Timeout,
)


class TestHashAlgorithm(FiberTest):
    """
    Test new_invoice hash_algorithm: omit (default), sha256, ckb_hash, and invalid value (other) rejected.
    """

    def test_none(self):
        """
        Omit hash_algorithm: default should work; create invoice, send payment, assert success and balance.
        Step 1: Open channel and wait CHANNEL_READY.
        Step 2: Create invoice without hash_algorithm; send payment; wait success and invoice paid; assert balance.
        """
        # Step 1: Open channel and wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice without hash_algorithm; send payment; assert success and balance
        amount = 1
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(amount),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel = self.fiber1.get_client().list_channels({})
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS
        )
        self.wait_invoice_state(
            self.fiber2, payment["payment_hash"], InvoiceStatus.PAID,
            timeout=Timeout.CHANNEL_READY
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            == int(after_channel["channels"][0]["local_balance"], 16) + amount
        )

    def test_sha256(self):
        """
        hash_algorithm sha256: create invoice, send payment, assert success and balance.
        Step 1: Open channel and wait CHANNEL_READY.
        Step 2: Create invoice with hash_algorithm sha256; send payment; wait success and invoice paid; assert balance.
        """
        # Step 1: Open channel and wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice with sha256; send payment; assert success and balance
        amount = 1
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(amount),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel = self.fiber1.get_client().list_channels({})
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS
        )
        self.wait_invoice_state(
            self.fiber2, payment["payment_hash"], InvoiceStatus.PAID,
            timeout=Timeout.CHANNEL_READY
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            == int(after_channel["channels"][0]["local_balance"], 16) + amount
        )

    def test_ckb_hash(self):
        """
        hash_algorithm ckb_hash: create invoice, send payment, assert success and balance.
        Step 1: Open channel and wait CHANNEL_READY.
        Step 2: Create invoice with hash_algorithm ckb_hash; send payment; wait success and invoice paid; assert balance.
        """
        # Step 1: Open channel and wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice with ckb_hash; send payment; assert success and balance
        amount = 1
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(amount),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "ckb_hash",
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel = self.fiber1.get_client().list_channels({})
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS
        )
        self.wait_invoice_state(
            self.fiber2, payment["payment_hash"], InvoiceStatus.PAID,
            timeout=Timeout.CHANNEL_READY
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            == int(after_channel["channels"][0]["local_balance"], 16) + amount
        )

    def test_other(self):
        """
        Invalid hash_algorithm "other" should raise with "Invalid params".
        Step 1: Call new_invoice with hash_algorithm "other"; expect exception containing "Invalid params".
        """
        # Step 1: Call new_invoice with invalid hash_algorithm; expect "Invalid params"
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "final_cltv": "0x28",
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": "other",
                }
            )
        expected_error_message = "Invalid params"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
