"""
Test cases for new_invoice / invoice cost: Expired, Paid (one succeeds one fails), Cancelled, and concurrent pay same invoice (one Success one Failed).
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    HashAlgorithm,
    InvoiceStatus,
    PaymentStatus,
    Timeout,
)


class TestInvoiceStatus(FiberTest):
    """
    Test invoice status flows: Expired (send_payment rejects), Paid (second pay fails), Cancelled, and cost invoice (concurrent pay; one Success one Failed).
    """

    def test_Expired(self):
        """
        Expired invoice: get_invoice status Expired; send_payment expects "invoice is expired".
        Then create valid invoice and pay; then concurrent pay from fiber2 and fiber3, one Success one Failed.
        Then Cancelled invoice: cancel then send_payment; then 10x concurrent pay same invoice from fiber2 and fiber3, assert one Success one Failed.
        Step 1: Build topology fiber3-fiber1-fiber2 and open channels.
        Step 2: Create invoice with expiry 0x0; assert status Expired; send_payment expects "invoice is expired".
        Step 3: Create invoice with normal expiry; fiber2 pays and succeeds; fiber3 pays same invoice and should fail.
        Step 4: Create invoice; cancel it; fiber2 send_payment (no wait).
        Step 5: Loop 10x: create invoice, fiber2 and fiber3 both send_payment, wait both finished; assert statuses differ (one Success one Failed).
        """
        # Step 1: Build topology fiber3-fiber1-fiber2 and open channels
        self.fiber3 = self.start_new_fiber(self.generate_account(10000))
        self.open_channel(
            self.fiber3, self.fiber1,
            fiber1_balance=Amount.ckb(1000),
            fiber2_balance=Amount.ckb(1000),
        )
        self.open_channel(
            self.fiber1, self.fiber2,
            fiber1_balance=Amount.ckb(1000),
            fiber2_balance=Amount.ckb(1000),
        )

        # Step 2: Create invoice with expiry 0x0; assert Expired; send_payment expects "invoice is expired"
        preimage = self.generate_random_preimage()
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0x0",
                "final_cltv": "0x28",
                "payment_preimage": preimage,
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        result = self.fiber1.get_client().get_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )
        assert result["status"] == InvoiceStatus.EXPIRED
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        expected_error_message = "invoice is expired"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 3: Create invoice with normal expiry; fiber2 pays success; fiber3 pays same invoice and should fail
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xffff",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        payment = self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber2, payment["payment_hash"], PaymentStatus.SUCCESS,
            timeout=Timeout.PAYMENT_SUCCESS
        )
        payment3 = self.fiber3.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber3, payment3["payment_hash"], PaymentStatus.FAILED,
            timeout=Timeout.CHANNEL_READY
        )

        # Step 4: Create invoice; cancel it; fiber2 send_payment
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xffff",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
            }
        )
        self.fiber1.get_client().cancel_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )
        self.fiber2.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        time.sleep(3)

        # Step 5: Loop 10x: create invoice, fiber2 and fiber3 both pay; wait both finished; assert one Success one Failed
        for _ in range(10):
            invoice = self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(1),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "payment_preimage": self.generate_random_preimage(),
                    "hash_algorithm": HashAlgorithm.SHA256,
                }
            )
            payment2 = self.fiber2.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
            payment3 = self.fiber3.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
            self.wait_payment_finished(self.fiber2, payment2["payment_hash"])
            self.wait_payment_finished(self.fiber3, payment3["payment_hash"])
            pay2 = self.fiber2.get_client().get_payment(
                {"payment_hash": payment2["payment_hash"]}
            )
            pay3 = self.fiber3.get_client().get_payment(
                {"payment_hash": payment3["payment_hash"]}
            )
            assert pay2["status"] != pay3["status"], "One should succeed and one fail (no double spend)"
