"""
Test cases for atomic MPP payment with different hash_algorithm (none, sha256, ckb_hash).
"""
from framework.basic_fiber import FiberTest
from framework.constants import Amount, Currency, HashAlgorithm, PaymentStatus, Timeout


class TestHashAlgorithm(FiberTest):
    """
    Test atomic MPP payment with hash_algorithm: none (default), sha256, ckb_hash.
    Each variant: create invoice, send payment with amp twice, wait for success.
    """

    def test_hash_algorithm_none_sha256_ckb_hash(self):
        """
        Pay same AMP invoice twice for hash_algorithm none, sha256, and ckb_hash.
        Step 1: Open channels, create invoice with no hash_algorithm, pay twice with amp.
        Step 2: Create invoice with hash_algorithm sha256, pay twice with amp.
        Step 3: Create invoice with hash_algorithm ckb_hash, pay twice with amp.
        """
        # Step 1: none (default) - open channels, invoice without hash_algorithm, pay twice
        for _ in range(3):
            self.open_channel(self.fiber1, self.fiber2, Amount.ckb(1000), Amount.ckb(0))

        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "allow_atomic_mpp": True,
            }
        )
        for _ in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"], "amp": True}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"],
                PaymentStatus.SUCCESS,
                timeout=Timeout.PAYMENT_SUCCESS,
            )

        # Step 2: sha256 - create invoice with hash_algorithm sha256, pay twice
        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "hash_algorithm": HashAlgorithm.SHA256,
                "allow_atomic_mpp": True,
            }
        )
        for _ in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"], "amp": True}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"],
                PaymentStatus.SUCCESS,
                timeout=Timeout.PAYMENT_SUCCESS,
            )

        # Step 3: ckb_hash - create invoice with hash_algorithm ckb_hash, pay twice
        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "hash_algorithm": HashAlgorithm.CKB_HASH,
                "allow_atomic_mpp": True,
            }
        )
        for _ in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"], "amp": True}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"],
                PaymentStatus.SUCCESS,
                timeout=Timeout.PAYMENT_SUCCESS,
            )
