"""
Test cases for new_invoice with atomic MPP.
Verifies payment_preimage conflict and invoice feature attrs; cancelled/expired invoice rejection.
"""
import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Currency, InvoiceStatus


class TestNewInvoice(FiberTest):
    """
    Test new_invoice with allow_atomic_mpp: payment_preimage not allowed; feature attrs;
    cancelled and expired invoice rejection on send_payment.
    """

    def test_new_invoice(self):
        """
        new_invoice with payment_preimage and allow_atomic_mpp must raise; valid invoice has ATOMIC_MPP_OPTIONAL.
        Step 1: Call new_invoice with payment_preimage and allow_atomic_mpp, expect error.
        Step 2: Assert error message contains "Both payment_hash and payment_preimage are set".
        Step 3: Create valid invoice with allow_atomic_mpp; assert feature attrs contain ATOMIC_MPP_OPTIONAL.
        """
        # Step 1: Call new_invoice with payment_preimage and allow_atomic_mpp, expect error
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().new_invoice(
                {
                    "amount": hex(Amount.ckb(1)),
                    "currency": Currency.FIBD,
                    "description": "test invoice generated by node2",
                    "expiry": "0xe10",
                    "payment_preimage": self.generate_random_preimage(),
                    "allow_atomic_mpp": True,
                }
            )

        # Step 2: Assert error message contains expected text
        expected_error_message = "Both payment_hash and payment_preimage are set"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 3: Create valid invoice and assert feature attrs contain ATOMIC_MPP_OPTIONAL
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "allow_atomic_mpp": True,
            }
        )
        assert {"feature": ["ATOMIC_MPP_OPTIONAL"]} in invoice["invoice"]["data"]["attrs"]

    def test_illegal_invoice(self):
        """
        Cancelled invoice and expired invoice should cause send_payment to fail with expected errors.
        Step 1: Open channel and create invoice; cancel it; send_payment expects "Failed to build route".
        Step 2: Create invoice with expiry 0x0; send_payment expects "invoice is expired".
        """
        # Step 1: Open channel, create and cancel invoice; send_payment should fail
        self.open_channel(self.fiber1, self.fiber2, Amount.ckb(1000), Amount.ckb(0))
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "allow_atomic_mpp": True,
            }
        )
        self.fiber1.get_client().cancel_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )
        self.fiber1.get_client().get_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().send_payment(
                {"invoice": invoice["invoice_address"], "amp": True}
            )
        expected_error_message = "Failed to build route"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 2: Create expired invoice; send_payment should fail with "invoice is expired"
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "expiry": "0x0",
                "description": "test invoice generated by node2",
                "allow_atomic_mpp": True,
            }
        )
        with pytest.raises(Exception) as exc_info:
            self.fiber2.get_client().send_payment(
                {"invoice": invoice["invoice_address"], "amp": True}
            )
        expected_error_message = "invoice is expired"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
