"""
Test cases for duplicate invoice payment (atomic MPP).
Verifies AMP invoice requires amp flag and same invoice can be paid multiple times.
"""
import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Amount, PaymentStatus, Timeout


class TestDupInvoice(FiberTest):
    """
    Test sending payment to same AMP invoice multiple times.
    Expect: without amp flag, send_payment fails; with amp flag, same invoice can be paid twice.
    """

    def test_dup_invoice(self):
        """
        AMP invoice: send without amp flag fails; send with amp twice succeeds and balance doubles.
        Step 1: Open channel and create AMP invoice on fiber2.
        Step 2: Send payment without amp flag, expect error about AMP invoice.
        Step 3: Send payment with amp flag twice, wait for success each time.
        Step 4: Assert fiber2 local balance equals 2 * invoice amount.
        """
        # Step 1: Open channel and create AMP invoice on fiber2
        for _ in range(3):
            self.open_channel(self.fiber1, self.fiber2, Amount.ckb(1000), Amount.ckb(0))

        fiber2_invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1001)),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "hash_algorithm": "sha256",
                "allow_atomic_mpp": True,
            }
        )

        # Step 2: Send payment without amp flag, expect error
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"]}
            )
        expected_error_message = (
            "It is a AMP invoice, need to set amp flag in SendPayment"
        )
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

        # Step 3: Send payment with amp flag twice, wait for success
        for _ in range(2):
            payment = self.fiber1.get_client().send_payment(
                {"invoice": fiber2_invoice["invoice_address"], "amp": True}
            )
            self.wait_payment_state(
                self.fiber1, payment["payment_hash"],
                PaymentStatus.SUCCESS,
                timeout=Timeout.PAYMENT_SUCCESS,
            )

        # Step 4: Assert fiber2 local balance equals 2 * invoice amount
        fiber2_balance = self.get_fiber_balance(self.fiber2)
        assert fiber2_balance["ckb"]["local_balance"] == Amount.ckb(2002)
