"""
Test cases for atomic MPP multi-node payment.
Multiple payers send to one atomic invoice; each payment gets a distinct payment_hash.
"""
from framework.basic_fiber import FiberTest
from framework.constants import Amount, PaymentStatus, Timeout


class TestMutilNodePayment(FiberTest):
    """
    Test multiple nodes paying the same atomic invoice.
    Each sender gets a unique payment_hash; all payments should succeed.
    """

    def test_mutil_node_payment(self):
        """
        Multiple payers send to one atomic invoice; expect N+1 distinct payment hashes and all succeed.
        Step 1: Start N extra fibers and open channels from fiber1 to each.
        Step 2: Create one atomic invoice on fiber1.
        Step 3: Each other fiber sends payment to that invoice (amp=True).
        Step 4: Assert N+1 distinct payment hashes and wait for all payments to succeed.
        """
        num_extra = 2
        # Step 1: Start extra fibers and open channels from fiber1 to each
        for _ in range(num_extra):
            self.start_new_fiber(self.generate_account(Amount.ckb(10000)))
        for i in range(1, len(self.fibers)):
            self.open_channel(
                self.fiber1,
                self.fibers[i],
                Amount.ckb(1000),
                Amount.ckb(1000),
            )

        # Step 2: Create one atomic invoice on fiber1
        atomic_invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(Amount.ckb(1)),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "hash_algorithm": "sha256",
                "allow_atomic_mpp": True,
            }
        )

        # Step 3: Each other fiber sends payment to that invoice (amp=True)
        payments = set()
        payment_list = []
        for i in range(1, len(self.fibers)):
            payment = self.fibers[i].get_client().send_payment(
                {"invoice": atomic_invoice["invoice_address"], "amp": True}
            )
            payments.add(payment["payment_hash"])
            payment_list.append(payment["payment_hash"])

        # Step 4: Assert N+1 distinct payment hashes and wait for all to succeed
        assert len(payments) == num_extra + 1, "Expected N+1 distinct payment hashes"
        for i, payment_hash in enumerate(payment_list):
            self.wait_payment_state(
                self.fibers[i + 1],
                payment_hash,
                status=PaymentStatus.SUCCESS,
                timeout=Timeout.PAYMENT_SUCCESS,
            )
