"""
update_channel tests: channel_id validation (not found vs existing channel).
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Timeout, ChannelState, PaymentStatus, Currency

TLC_FEE_MILLIONTHS = 2000  # 0.2%


class TestChannelId(FiberTest):
    """
    Test update_channel with invalid channel_id (not found) and with valid channel_id (fee update and payment).
    """

    def test_channel_id_not_exist(self):
        """
        update_channel with non-existent channel_id should raise with 'Channel not found error'.
        Step 1: Call update_channel with random preimage as channel_id.
        Step 2: Assert exception message contains 'Channel not found error'.
        """
        # Step 1: Call update_channel with non-existent channel_id
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().update_channel(
                {"channel_id": self.generate_random_preimage()}
            )
        # Step 2: Assert exception message contains expected substring
        expected = "Channel not found error"
        assert expected in exc_info.value.args[0], (
            f"Expected substring '{expected}' not found in '{exc_info.value.args[0]}'"
        )

    def test_channel_id_exist(self):
        """
        F3-F1 and F1-F2 channels; F1 pays F2; F1 updates F1-F2 tlc_fee to 2000; F3 pays F2; assert fee applied.
        Step 1: Start F3, open F3-F1 channel; wait CHANNEL_READY.
        Step 2: Open F1-F2 channel; wait CHANNEL_READY.
        Step 3: F1 send_payment F2 (invoice); wait Success; assert balance change.
        Step 4: F1 update_channel F1-F2 (channel_id from F2) tlc_fee_proportional_millionths 2000.
        Step 5: F3 send_payment F2 (invoice); wait Success; assert F3 balance includes fee, F2 receives amount.
        """
        # Step 1: Start F3, open F3-F1 channel; wait CHANNEL_READY
        account3_private = self.generate_account(1000)
        self.fiber3 = self.start_new_fiber(account3_private)
        self.fiber3.connect_peer(self.fiber1)
        time.sleep(Timeout.POLL_INTERVAL)
        self.fiber3.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Open F1-F2 channel; wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 3: F1 send_payment F2 (invoice); wait Success; assert balance change
        invoice_balance = Amount.ckb(1)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel = self.fiber1.get_client().list_channels({})
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS, timeout=Timeout.CHANNEL_READY
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert int(before_channel["channels"][0]["local_balance"], 16) - int(
            after_channel["channels"][0]["local_balance"], 16
        ) == invoice_balance

        # Step 4: F1 update_channel F1-F2 (channel_id from F2) tlc_fee_proportional_millionths 2000
        before2_channel = self.fiber2.get_client().list_channels({})
        self.fiber1.get_client().update_channel(
            {
                "channel_id": before2_channel["channels"][0]["channel_id"],
                "tlc_fee_proportional_millionths": hex(TLC_FEE_MILLIONTHS),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)

        # Step 5: F3 send_payment F2 (invoice); wait Success; assert F3 balance includes fee, F2 receives amount
        invoice_balance_hex = hex(Amount.ckb(1))
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance_hex,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel31 = self.fiber3.get_client().list_channels({})
        before_channel21 = self.fiber2.get_client().list_channels({})
        payment = self.fiber3.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber3, payment["payment_hash"], PaymentStatus.SUCCESS, timeout=Timeout.CHANNEL_READY
        )
        after_channel31 = self.fiber3.get_client().list_channels({})
        after_channel21 = self.fiber2.get_client().list_channels({})
        amt = int(invoice_balance_hex, 16)
        expected_fee = int(amt * (TLC_FEE_MILLIONTHS / 1_000_000))
        assert int(before_channel31["channels"][0]["local_balance"], 16) - int(
            after_channel31["channels"][0]["local_balance"], 16
        ) == amt + expected_fee
        assert int(after_channel21["channels"][0]["local_balance"], 16) - int(
            before_channel21["channels"][0]["local_balance"], 16
        ) == amt
