"""
update_channel tests: combined params (channel_id, enabled, tlc_minimum_value, tlc_fee_proportional_millionths)
and multi-hop payment after repeated fee updates.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Timeout, ChannelState, PaymentStatus, Currency

TLC_FEE_2000 = 2000
TLC_MIN_BELOW_AMOUNT = 100 - 10  # tlc_minimum_value 100, invoice amount 90 should fail route


class TestUpdateChannel(FiberTest):
    """
    Test update_channel with combined params and behavior: channel_id, enabled, tlc_expiry_delta,
    tlc_minimum_value, tlc_fee_proportional_millionths; update in pending/open/closed; graph_channel checks.
    """

    def test_01(self):
        """
        F3-F1, F1-F2; F1 pays F2; F1 update_channel (enabled True, tlc_minimum_value 100, tlc_fee 1000);
        F3 pay F2 with amount below tlc_minimum_value fails 'Failed to build route'; graph_channels check.
        Step 1: Start F3, open F3-F1 and F1-F2; wait CHANNEL_READY.
        Step 2: F1 send_payment F2 (1 CKB); wait Success; assert balance.
        Step 3: F1 update_channel F1-F2 (channel_id from F2, enabled True, tlc_minimum_value 100, tlc_fee 1000).
        Step 4: F3 send_payment F2 (tlc_minimum_value - 10); expect 'Failed to build route'.
        Step 5: Assert graph_channels (tlc_fee check).
        """
        # Step 1: Start F3, open F3-F1 and F1-F2; wait CHANNEL_READY
        account3_private = self.generate_account(1000)
        self.fiber3 = self.start_new_fiber(account3_private)
        self.fiber3.connect_peer(self.fiber1)
        time.sleep(Timeout.POLL_INTERVAL)
        self.fiber3.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: F1 send_payment F2 (1 CKB); wait Success; assert balance
        invoice_balance = hex(Amount.ckb(1))
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel = self.fiber1.get_client().list_channels({})
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS, timeout=Timeout.CHANNEL_READY
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert int(before_channel["channels"][0]["local_balance"], 16) - int(
            after_channel["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        channel2 = self.fiber2.get_client().list_channels({})
        update_channel_param = {
            "enabled": True,
            "tlc_minimum_value": hex(100),
            "tlc_fee_proportional_millionths": hex(1000),
        }
        update_channel_param["channel_id"] = channel2["channels"][0]["channel_id"]
        self.fiber1.get_client().update_channel(update_channel_param)
        time.sleep(Timeout.POLL_INTERVAL)

        # Step 3 & 4: F3 send_payment F2 with amount below tlc_minimum_value; expect 'Failed to build route'
        invoice_below = hex(TLC_MIN_BELOW_AMOUNT)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_below,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        with pytest.raises(Exception) as exc_info:
            self.fiber3.get_client().send_payment(
                {"invoice": invoice["invoice_address"]}
            )
        expected = "Failed to build route"
        assert expected in exc_info.value.args[0], (
            f"Expected '{expected}' not found in '{exc_info.value.args[0]}'"
        )

        # Step 5: graph_channels check
        self.fiber3.get_client().graph_channels()

    def test_m(self):
        """
        Build ring of fibers; open channels between consecutive nodes; repeatedly update tlc_fee_proportional_millionths;
        send keysend from first to last; wait Success.
        Step 1: Start 2 more fibers; connect all in a ring; open channel between each pair; wait CHANNEL_READY.
        Step 2: For each channel, update tlc_fee 100 times (2000+i); brief sleep.
        Step 3: Send keysend from first to last node; wait Success.
        """
        # Step 1: Start 2 more fibers; connect in ring; open channel between each pair
        for _ in range(2):
            account_private = self.generate_account(1000)
            fiber = self.start_new_fiber(account_private)
            fiber.connect_peer(self.fiber1)
            fiber.connect_peer(self.fiber2)
        for i in range(len(self.fibers) - 1):
            linked_fiber = self.fibers[(i + 1) % len(self.fibers)]
            current_fiber = self.fibers[i]
            linked_fiber.connect_peer(current_fiber)
            time.sleep(Timeout.POLL_INTERVAL)
            current_fiber.get_client().open_channel(
                {
                    "peer_id": linked_fiber.get_peer_id(),
                    "funding_amount": hex(Amount.ckb(500)),
                    "public": True,
                }
            )
            self.wait_for_channel_state(
                current_fiber.get_client(),
                linked_fiber.get_peer_id(),
                ChannelState.CHANNEL_READY,
                timeout=Timeout.CHANNEL_READY,
            )
            for j in range(100):
                linked_fiber.get_client().update_channel(
                    {
                        "channel_id": current_fiber.get_client().list_channels({})["channels"][0]["channel_id"],
                        "tlc_fee_proportional_millionths": hex(TLC_FEE_2000 + j),
                    }
                )
                time.sleep(0.02)
            self.wait_for_channel_state(
                current_fiber.get_client(),
                linked_fiber.get_peer_id(),
                ChannelState.CHANNEL_READY,
                timeout=Timeout.CHANNEL_READY,
            )
        time.sleep(Timeout.POLL_INTERVAL)

        # Step 2 & 3: Send keysend from first to last; wait Success
        pub_key = self.fibers[-1].get_client().node_info()["node_id"]
        payment = self.fibers[0].get_client().send_payment(
            {
                "target_pubkey": pub_key,
                "amount": hex(Amount.ckb(10)),
                "keysend": True,
            }
        )
        self.wait_payment_state(
            self.fibers[0], payment["payment_hash"], PaymentStatus.SUCCESS, timeout=Timeout.PAYMENT_SUCCESS
        )
