"""
update_channel tests: tlc_fee_proportional_millionths (0, normal, overflow, max) and fee effect on payment.
"""
import time

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Amount, Timeout, ChannelState, PaymentStatus, Currency

TLC_FEE_2000 = 2000  # 0.2%
TLC_FEE_0 = 0
# u128::MAX compatible value used in test_max
TLC_FEE_U128_MAX = 340282366920938463


class TestTlcFeeProportionalMillionths(FiberTest):
    """
    Test update_channel tlc_fee_proportional_millionths: zero fee, normal fee (balance assertions), overflow reject, max value in graph.
    """

    def test_0x0(self):
        """
        F3-F1, F1-F2; F1 pays F2; F1 updates F1-F2 tlc_fee to 0; F3 pays F2; assert F3 balance change equals amount (no fee), F2 receives amount.
        Step 1: Start F3, open F3-F1 and F1-F2; wait CHANNEL_READY.
        Step 2: F1 send_payment F2 (invoice); wait Success; assert balance.
        Step 3: F1 update_channel F1-F2 tlc_fee_proportional_millionths 0.
        Step 4: F3 send_payment F2 (invoice); wait Success; assert F3 debit = amount + 0, F2 credit = amount.
        """
        # Step 1: Start F3, open F3-F1 and F1-F2; wait CHANNEL_READY
        account3_private = self.generate_account(1000)
        self.fiber3 = self.start_new_fiber(account3_private)
        self.fiber3.connect_peer(self.fiber1)
        time.sleep(Timeout.POLL_INTERVAL)
        self.fiber3.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: F1 send_payment F2 (invoice); wait Success; assert balance
        invoice_balance = hex(Amount.ckb(1))
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel = self.fiber1.get_client().list_channels({})
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS, timeout=Timeout.CHANNEL_READY
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert int(before_channel["channels"][0]["local_balance"], 16) - int(
            after_channel["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        before2_channel = self.fiber2.get_client().list_channels({})
        self.fiber1.get_client().update_channel(
            {
                "channel_id": before2_channel["channels"][0]["channel_id"],
                "tlc_fee_proportional_millionths": hex(TLC_FEE_0),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)

        # Step 3 & 4: F3 send_payment F2; wait Success; assert F3 debit = amount + 0, F2 credit = amount
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel31 = self.fiber3.get_client().list_channels({})
        before_channel21 = self.fiber2.get_client().list_channels({})
        payment = self.fiber3.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber3, payment["payment_hash"], PaymentStatus.SUCCESS, timeout=Timeout.CHANNEL_READY
        )
        after_channel31 = self.fiber3.get_client().list_channels({})
        after_channel21 = self.fiber2.get_client().list_channels({})
        amt = int(invoice_balance, 16)
        expected_fee = int(amt * (TLC_FEE_0 / 1_000_000))
        assert int(before_channel31["channels"][0]["local_balance"], 16) - int(
            after_channel31["channels"][0]["local_balance"], 16
        ) == amt + expected_fee
        assert int(after_channel21["channels"][0]["local_balance"], 16) - int(
            before_channel21["channels"][0]["local_balance"], 16
        ) == amt

    def test_overflow(self):
        """
        Open F1-F2; update_channel tlc_fee_proportional_millionths overflow hex; expect 'Invalid params'.
        Step 1: Open F1-F2; wait CHANNEL_READY.
        Step 2: update_channel with overflow hex; assert exception contains 'Invalid params'.
        """
        # Step 1: Open F1-F2; wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        channels = self.fiber1.get_client().list_channels({})
        # Step 2: update_channel with overflow hex; assert 'Invalid params'
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().update_channel(
                {
                    "channel_id": channels["channels"][0]["channel_id"],
                    "tlc_fee_proportional_millionths": "0xfffffffffffffffffffffffffffffffff",
                }
            )
        assert "Invalid params" in exc_info.value.args[0], (
            f"Expected 'Invalid params' not found in '{exc_info.value.args[0]}'"
        )

    def test_max(self):
        """
        Open F1-F2; update F1 and F2 tlc_fee to u128::MAX-compatible value; assert graph_channels fee_rate.
        Step 1: Open F1-F2; wait CHANNEL_READY.
        Step 2: F1 update_channel tlc_fee_proportional_millionths to TLC_FEE_U128_MAX; F2 same; wait.
        Step 3: Assert graph_channels update_info_of_node1/update_info_of_node2 fee_rate.
        """
        # Step 1: Open F1-F2; wait CHANNEL_READY
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        channels = self.fiber1.get_client().list_channels({})
        ch_id = channels["channels"][0]["channel_id"]

        # Step 2: F1 and F2 update_channel tlc_fee to TLC_FEE_U128_MAX
        self.fiber1.get_client().update_channel(
            {"channel_id": ch_id, "tlc_fee_proportional_millionths": hex(TLC_FEE_U128_MAX)}
        )
        time.sleep(3)
        self.fiber2.get_client().update_channel(
            {"channel_id": ch_id, "tlc_fee_proportional_millionths": hex(TLC_FEE_U128_MAX)}
        )
        time.sleep(3)

        # Step 3: Assert graph_channels fee_rate
        graph_channels = self.fiber1.get_client().graph_channels()
        assert graph_channels["channels"][0]["update_info_of_node2"]["fee_rate"] == hex(TLC_FEE_U128_MAX)
        assert graph_channels["channels"][0]["update_info_of_node1"]["fee_rate"] == hex(TLC_FEE_U128_MAX)

    def test_normal(self):
        """
        F3-F1, F1-F2; F1 pays F2; F1 updates F1-F2 tlc_fee to 2000; F3 pays F2; assert F3 balance includes fee, F2 receives amount.
        Step 1: Start F3, open F3-F1 and F1-F2; wait CHANNEL_READY.
        Step 2: F1 send_payment F2 (invoice); wait Success; assert balance.
        Step 3: F1 update_channel F1-F2 tlc_fee_proportional_millionths 2000.
        Step 4: F3 send_payment F2 (invoice); wait Success; assert F3 debit = amount + fee, F2 credit = amount.
        """
        # Step 1: Start F3, open F3-F1 and F1-F2; wait CHANNEL_READY
        account3_private = self.generate_account(1000)
        self.fiber3 = self.start_new_fiber(account3_private)
        self.fiber3.connect_peer(self.fiber1)
        time.sleep(Timeout.POLL_INTERVAL)
        self.fiber3.get_client().open_channel(
            {
                "peer_id": self.fiber1.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber3.get_client(),
            self.fiber1.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: F1 send_payment F2 (invoice); wait Success; assert balance
        invoice_balance = hex(Amount.ckb(1))
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel = self.fiber1.get_client().list_channels({})
        payment = self.fiber1.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS, timeout=Timeout.CHANNEL_READY
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert int(before_channel["channels"][0]["local_balance"], 16) - int(
            after_channel["channels"][0]["local_balance"], 16
        ) == int(invoice_balance, 16)

        before2_channel = self.fiber2.get_client().list_channels({})
        self.fiber1.get_client().update_channel(
            {
                "channel_id": before2_channel["channels"][0]["channel_id"],
                "tlc_fee_proportional_millionths": hex(TLC_FEE_2000),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)

        # Step 3 & 4: F3 send_payment F2; wait Success; assert F3 debit = amount + fee, F2 credit = amount
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": invoice_balance,
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
            }
        )
        time.sleep(Timeout.POLL_INTERVAL)
        before_channel31 = self.fiber3.get_client().list_channels({})
        before_channel21 = self.fiber2.get_client().list_channels({})
        payment = self.fiber3.get_client().send_payment(
            {"invoice": invoice["invoice_address"]}
        )
        self.wait_payment_state(
            self.fiber3, payment["payment_hash"], PaymentStatus.SUCCESS, timeout=Timeout.CHANNEL_READY
        )
        after_channel31 = self.fiber3.get_client().list_channels({})
        after_channel21 = self.fiber2.get_client().list_channels({})
        amt = int(invoice_balance, 16)
        expected_fee = int(amt * (TLC_FEE_2000 / 1_000_000))
        assert int(before_channel31["channels"][0]["local_balance"], 16) - int(
            after_channel31["channels"][0]["local_balance"], 16
        ) == amt + expected_fee
        assert int(after_channel21["channels"][0]["local_balance"], 16) - int(
            before_channel21["channels"][0]["local_balance"], 16
        ) == amt
