"""
Fiber demo tests: UDT channel, CKB channel, multi-hop payment.
Basic flow: open channel -> transfer -> close channel -> verify balance.
"""
import time

from framework.basic_fiber import FiberTest
from framework.constants import (
    Amount,
    ChannelState,
    Currency,
    FeeRate,
    PaymentStatus,
    Timeout,
)


class TestFiberDemo(FiberTest):
    """
    Fiber demo tests for UDT channel, CKB channel, and multi-hop payment.
    Covers basic open/transfer/close flow and balance verification.
    """

    def test_udt(self):
        """
        Test UDT channel: open -> transfer -> close -> verify balance.
        Step 1: Open UDT channel between fiber1 and fiber2.
        Step 2: Create invoice and send payment.
        Step 3: Shutdown channel and wait for close tx.
        Step 4: Assert UDT balance is correct after close.
        """
        # Step 1: Open UDT channel between fiber1 and fiber2
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
                "funding_udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice and send payment
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(100)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        # Step 3: Shutdown channel and wait for close tx
        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        before_account1 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        before_account2 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": hex(FeeRate.DEFAULT),
            }
        )
        time.sleep(Timeout.SHORT)

        # Step 4: Assert UDT balance is correct after close
        after_account1 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        after_account2 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )

        assert after_account1[-1]["balance"] == Amount.ckb(900)
        print(after_account2)
        assert after_account2[-1]["balance"] == Amount.ckb(100)

    def test_ckb(self):
        """
        Test CKB channel: open -> transfer -> close -> verify balance.
        Step 1: Open CKB channel between fiber1 and fiber2.
        Step 2: Create invoice and send payment.
        Step 3: Shutdown channel and verify CKB balance.
        """
        # Step 1: Open CKB channel between fiber1 and fiber2
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 2: Create invoice and send payment
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(100)
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS
        )
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        # Step 3: Shutdown channel and verify CKB balance
        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": hex(FeeRate.DEFAULT),
            }
        )
        before_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        time.sleep(Timeout.SHORT)
        after_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.fiber1.get_account()["address"]["testnet"]
        )
        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.fiber2.get_account()["address"]["testnet"]
        )
        print("before_balance1:", before_balance1)
        print("before_balance2:", before_balance2)
        print("after_balance1:", after_balance1)
        print("after_balance2:", after_balance2)

    def test_new_fiber_test(self):
        """
        Test multi-hop payment: fiber1->fiber2->fiber3.
        Step 1: Start fiber3 and connect to fiber2.
        Step 2: Open channels fiber1->fiber2 and fiber2->fiber3.
        Step 3: Create invoice on fiber3 and send payment from fiber1.
        Step 4: Verify payment success.
        """
        # Step 1: Start fiber3 and connect to fiber2
        account3_privake_key = self.generate_account(1000)
        fiber3 = self.start_new_fiber(account3_privake_key)
        fiber3.connect_peer(self.fiber2)
        time.sleep(3)

        # Step 2: Open channels fiber1->fiber2 and fiber2->fiber3
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(),
            self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )
        self.fiber2.get_client().open_channel(
            {
                "peer_id": fiber3.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(),
            fiber3.get_peer_id(),
            ChannelState.CHANNEL_READY,
            timeout=Timeout.CHANNEL_READY,
        )

        # Step 3: Create invoice on fiber3 and send payment from fiber1
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(100)
        invoice = fiber3.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )

        # Step 4: Verify payment success
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(
            self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS
        )

        channelsN12 = self.fiber1.get_client().list_channels({})
        channelsN32 = fiber3.get_client().list_channels({})

    def test_faucet(self):
        """
        Test faucet: issue UDT and CKB to account.
        Step 1: Generate account and faucet UDT/CKB.
        Step 2: Assert balance is correct.
        """
        # Step 1: Generate account and faucet UDT/CKB
        account_private_key = self.generate_account(0)
        self.faucet(
            account_private_key,
            1000,
            self.fiber2.account_private,
            Amount.udt(1000),
        )

        # Step 2: Assert balance is correct
        ret = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber2.account_private)["args"],
            self.get_account_script(account_private_key)["args"],
        )

        assert ret[0]["balance"] == Amount.udt(100)
        assert ret[0]["ckb"] == Amount.ckb(500)
