"""
Fiber demo tests: UDT channel, CKB channel, multi-hop payment.
"""
import time

from framework.basic_fiber import FiberTest
from framework.constants import Amount, ChannelState, PaymentStatus, FeeRate, Timeout


class TestFiberDemo(FiberTest):
    # FiberTest.debug = True

    # clean env
    # pkill ckb
    # pkill fnn
    # rm -rf tmp

    def test_udt(self):
        """
        Test UDT channel: open, transfer, close, verify balance.
        Step 1: Open UDT channel between fiber1 and fiber2.
        Step 2: Create invoice and send payment.
        Step 3: Shutdown channel.
        Step 4: Assert UDT balance changes.
        """
        # Step 1: Open UDT channel
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(1000)),
                "public": True,
                "funding_udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(), "CHANNEL_READY", 120
        )
        # transfer
        payment_preimage = self.generate_random_preimage()
        invoice_balance = 100 * 100000000
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
                "udt_type_script": self.get_account_udt_script(
                    self.fiber1.account_private
                ),
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS)
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        before_account1 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        before_account2 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )
        # Step 3: Shutdown channel
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": hex(FeeRate.MEDIUM),
            }
        )
        time.sleep(20)

        after_account1 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber1.account_private)["args"],
        )
        after_account2 = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber1.account_private)["args"],
            self.get_account_script(self.fiber2.account_private)["args"],
        )

        assert after_account1[-1]["balance"] == Amount.ckb(900)
        print(after_account2)
        assert after_account2[-1]["balance"] == Amount.ckb(100)

    def test_ckb(self):
        """
        Test CKB channel: open, transfer, close, verify balance.
        Step 1: Open CKB channel between fiber1 and fiber2.
        Step 2: Create invoice and send payment.
        Step 3: Shutdown channel.
        Step 4: Verify CKB balance changes.
        """
        # Step 1: Open CKB channel
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
                # "tlc_fee_proportional_millionths": "0x4B0",
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(), "CHANNEL_READY", 120
        )
        # transfer
        payment_preimage = self.generate_random_preimage()
        invoice_balance = 100 * 100000000
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )
        before_channel = self.fiber1.get_client().list_channels({})

        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS)
        after_channel = self.fiber1.get_client().list_channels({})
        assert (
            int(before_channel["channels"][0]["local_balance"], 16)
            - int(after_channel["channels"][0]["local_balance"], 16)
            == invoice_balance
        )

        channels = self.fiber1.get_client().list_channels(
            {"peer_id": self.fiber2.get_peer_id()}
        )
        N1N2_CHANNEL_ID = channels["channels"][0]["channel_id"]
        self.fiber1.get_client().graph_channels()

        # shut down
        self.fiber1.get_client().shutdown_channel(
            {
                "channel_id": N1N2_CHANNEL_ID,
                "close_script": self.get_account_script(self.Config.ACCOUNT_PRIVATE_1),
                "fee_rate": "0x3FC",
            }
        )
        before_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.account1["address"]["testnet"]
        )
        before_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.account2["address"]["testnet"]
        )
        # todo wait close tx commit
        time.sleep(20)
        after_balance1 = self.Ckb_cli.wallet_get_capacity(
            self.fiber1.get_account()["address"]["testnet"]
        )
        after_balance2 = self.Ckb_cli.wallet_get_capacity(
            self.fiber2.get_account()["address"]["testnet"]
        )
        print("before_balance1:", before_balance1)
        print("before_balance2:", before_balance2)
        print("after_balance1:", after_balance1)
        print("after_balance2:", after_balance2)

    def test_new_fiber_test(self):
        """
        Test multi-hop payment: fiber1->fiber2->fiber3.
        Step 1: Start fiber3 and connect to fiber2.
        Step 2: Open channels fiber1-fiber2 and fiber2-fiber3.
        Step 3: Create invoice on fiber3 and send payment from fiber1.
        Step 4: Verify payment success.
        """
        # Step 1: Start fiber3
        account3_privake_key = self.generate_account(1000)
        fiber3 = self.start_new_fiber(account3_privake_key)

        #         2. 连接fiber3 和fiber2
        fiber3.connect_peer(self.fiber2)
        time.sleep(3)
        #         3. 1 openchan 2
        self.fiber1.get_client().open_channel(
            {
                "peer_id": self.fiber2.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY
        )
        # Step 2: Open channel fiber2-fiber3
        self.fiber2.get_client().open_channel(
            {
                "peer_id": fiber3.get_peer_id(),
                "funding_amount": hex(Amount.ckb(200)),
                "public": True,
            }
        )
        self.wait_for_channel_state(
            self.fiber2.get_client(), fiber3.get_peer_id(),
            ChannelState.CHANNEL_READY, Timeout.CHANNEL_READY
        )
        # Step 3: Create invoice and send payment
        payment_preimage = self.generate_random_preimage()
        invoice_balance = Amount.ckb(100)
        invoice = fiber3.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": payment_preimage,
                "hash_algorithm": "sha256",
            }
        )

        #         6. node1 transfer node3
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        # 8. query 是否成功
        self.wait_payment_state(self.fiber1, payment["payment_hash"], PaymentStatus.SUCCESS)
        # todo fiber3 query payment
        # self.wait_payment_state(fiber3, payment['payment_hash'], "Success")

        # check account
        channelsN12 = self.fiber1.get_client().list_channels({})
        channelsN32 = fiber3.get_client().list_channels({})
        #         9 shut down

    def test_faucet(self):
        """
        Test faucet: generate account, faucet UDT, verify balance.
        """
        account_private_key = self.generate_account(0)
        self.faucet(
            account_private_key,
            Amount.ckb(1000),
            self.fiber2.account_private,
            Amount.udt(100),  # 100 UDT
        )

        ret = self.udtContract.list_cell(
            self.node.getClient(),
            self.get_account_script(self.fiber2.account_private)["args"],
            self.get_account_script(account_private_key)["args"],
        )

        assert ret[0]["balance"] == Amount.ckb(100)
        assert ret[0]["ckb"] == Amount.ckb(500)
