import time

import pytest

from framework.basic_fiber import FiberTest
from framework.test_fiber import FiberConfigPath


class TestMaxTlcNumberInFlightDebug(FiberTest):
    fiber_version = FiberConfigPath.CURRENT_DEV_DEBUG

    def test_max_tlc_number_in_flight_none(self):
        """
        max_tlc_number_in_flight == none
        Returns:
        """
        self.fiber1.connect_peer(self.fiber2)
        time.sleep(5)
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(200 * 100000000),
                "public": True,
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        time.sleep(5)
        # transfer
        self.fiber1.get_client().graph_channels()
        self.fiber1.get_client().graph_nodes()
        channel_id = self.fiber1.get_client().list_channels({})["channels"][0][
            "channel_id"
        ]
        add_tlc_list = []
        invoice_count = 125
        # 获取当前时间戳
        invoice_balance = 10 * 100000000
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
            }
        )
        time.sleep(0.3)
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], "Success")

        for i in range(invoice_count):
            print("current :", i)
            payment_preimage = self.generate_random_preimage()
            add_tlc = self.fiber1.get_client().add_tlc(
                {
                    "channel_id": channel_id,
                    "amount": hex(100),
                    # "payment_hash": invoice_list[i]['invoice']['data']['payment_hash'],
                    "payment_hash": payment_preimage,
                    "expiry": hex((int(time.time()) + 1000) * 1000),
                    "hash_algorithm": "sha256",
                }
            )
            add_tlc_list.append(add_tlc)
            time.sleep(1)
        time.sleep(10)
        with pytest.raises(Exception) as exc_info:
            payment_preimage = self.generate_random_preimage()
            self.fiber1.get_client().add_tlc(
                {
                    "channel_id": channel_id,
                    "amount": hex(100),
                    # "payment_hash": invoice_list[i]['invoice']['data']['payment_hash'],
                    "payment_hash": payment_preimage,
                    "expiry": hex((int(time.time()) + 40) * 1000),
                    "hash_algorithm": "sha256",
                }
            )
        expected_error_message = "TemporaryChannelFailure"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
        self.fiber1.get_client().list_channels({})
        self.fiber2.get_client().list_channels({})

    def test_max_tlc_number_in_flight_not_eq_default(self):
        """
        max_tlc_number_in_flight != default
        Returns:
        """
        # max_tlc_number_in_flight_num = 15
        self.fiber1.connect_peer(self.fiber2)
        time.sleep(5)
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(200 * 100000000),
                "public": True,
                "max_tlc_number_in_flight": hex(16),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        time.sleep(5)
        # transfer
        self.fiber1.get_client().graph_channels()
        self.fiber1.get_client().graph_nodes()
        channel_id = self.fiber1.get_client().list_channels({})["channels"][0][
            "channel_id"
        ]
        add_tlc_list = []
        invoice_count = 16
        # 获取当前时间戳
        invoice_balance = 10 * 100000000
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
            }
        )
        time.sleep(1)
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], "Success")

        for i in range(invoice_count):
            print("current :", i)
            payment_preimage = self.generate_random_preimage()
            add_tlc = self.fiber1.get_client().add_tlc(
                {
                    "channel_id": channel_id,
                    "amount": hex(100),
                    # "payment_hash": invoice_list[i]['invoice']['data']['payment_hash'],
                    "payment_hash": payment_preimage,
                    "expiry": hex((int(time.time()) + 40) * 1000),
                    "hash_algorithm": "sha256",
                }
            )
            add_tlc_list.append(add_tlc)
            time.sleep(1)
        time.sleep(10)
        with pytest.raises(Exception) as exc_info:
            payment_preimage = self.generate_random_preimage()
            self.fiber1.get_client().add_tlc(
                {
                    "channel_id": channel_id,
                    "amount": hex(100),
                    # "payment_hash": invoice_list[i]['invoice']['data']['payment_hash'],
                    "payment_hash": payment_preimage,
                    "expiry": hex((int(time.time()) + 40) * 1000),
                    "hash_algorithm": "sha256",
                }
            )
        expected_error_message = "TemporaryChannelFailure"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )

    def test_max_tlc_number_in_flight_not_eq_default_other_node(self):
        """
        max_tlc_number_in_flight != default
        Returns:
        """
        # max_tlc_number_in_flight_num = 15
        self.fiber1.connect_peer(self.fiber2)
        time.sleep(5)
        temporary_channel_id = self.fiber1.get_client().open_channel(
            {
                "pubkey": self.fiber2.get_pubkey(),
                "funding_amount": hex(200 * 100000000),
                "public": True,
                "max_tlc_number_in_flight": hex(5),
            }
        )
        time.sleep(1)
        self.wait_for_channel_state(
            self.fiber1.get_client(), self.fiber2.get_pubkey(), "CHANNEL_READY", 120
        )
        time.sleep(5)
        # transfer
        self.fiber1.get_client().graph_channels()
        self.fiber1.get_client().graph_nodes()
        channel_id = self.fiber1.get_client().list_channels({})["channels"][0][
            "channel_id"
        ]
        # 获取当前时间戳
        invoice_balance = 10 * 100000000
        invoice = self.fiber2.get_client().new_invoice(
            {
                "amount": hex(invoice_balance),
                "currency": "Fibd",
                "description": "test invoice generated by node2",
                "expiry": "0xe10",
                "final_cltv": "0x28",
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": "sha256",
            }
        )
        time.sleep(1)
        payment = self.fiber1.get_client().send_payment(
            {
                "invoice": invoice["invoice_address"],
            }
        )
        self.wait_payment_state(self.fiber1, payment["payment_hash"], "Success")

        invoice_count = 10
        for i in range(invoice_count):
            print("current :", i)
            payment_preimage = self.generate_random_preimage()
            add_tlc = self.fiber2.get_client().add_tlc(
                {
                    "channel_id": channel_id,
                    "amount": hex(100),
                    # "payment_hash": invoice_list[i]['invoice']['data']['payment_hash'],
                    "payment_hash": payment_preimage,
                    "expiry": hex((int(time.time()) + 40) * 1000),
                    "hash_algorithm": "sha256",
                }
            )
            time.sleep(0.3)
