"""
Test cases for get_invoice RPC: get existing invoice and non-existent invoice.
"""
import datetime

import pytest

from framework.basic_fiber import FiberTest
from framework.constants import Currency, HashAlgorithm


class TestGetInvoice(FiberTest):
    """
    Test get_invoice RPC: query invoice by payment_hash, parse_invoice, and error for non-existent.
    """

    def test_get_exist_new_invoice(self):
        """
        Get existing new invoice and verify parse_invoice matches; verify node_id and fields.
        Step 1: Create a new invoice.
        Step 2: Retrieve the created invoice using its payment hash.
        Step 3: Verify the node ID matches the PayeePublicKey in the invoice.
        Step 4: Parse the invoice and verify the parsed result matches the original invoice.
        Step 5: Verify the timestamp of the invoice.
        """
        # Step 1: Create a new invoice
        invoice = self.fiber1.get_client().new_invoice(
            {
                "amount": hex(1),
                "currency": Currency.FIBD,
                "description": "test invoice generated by node2",
                "expiry": hex(3600),
                "final_cltv": hex(40),
                "payment_preimage": self.generate_random_preimage(),
                "hash_algorithm": HashAlgorithm.SHA256,
                "allow_mpp": True,
            }
        )

        # Step 2: Retrieve the created invoice using its payment hash
        result = self.fiber1.get_client().get_invoice(
            {"payment_hash": invoice["invoice"]["data"]["payment_hash"]}
        )
        node_info = self.fiber1.get_client().node_info()

        # Step 3: Verify the node ID matches the PayeePublicKey in the invoice
        assert (
            node_info["node_id"]
            == result["invoice"]["data"]["attrs"][-1]["payee_public_key"]
        )

        # Step 4: Parse the invoice and verify the parsed result matches the original invoice
        parse_invoice = self.fiber1.get_client().parse_invoice(
            {"invoice": invoice["invoice_address"]}
        )
        assert parse_invoice["invoice"] == invoice["invoice"]
        assert invoice["invoice"]["currency"] == Currency.FIBD
        assert invoice["invoice"]["amount"] == "0x1"
        assert (
            invoice["invoice"]["data"]["attrs"][0]["description"]
            == "test invoice generated by node2"
        )
        assert invoice["invoice"]["data"]["attrs"][1]["expiry_time"] == hex(3600)
        assert invoice["invoice"]["data"]["attrs"][5]["hash_algorithm"] == HashAlgorithm.SHA256

        # Step 5: Verify the timestamp of the invoice
        assert int(int(invoice["invoice"]["data"]["timestamp"], 16) / 1000) == int(
            datetime.datetime.now().timestamp()
        )

    def test_get_not_exist_invoice(self):
        """
        Query a non-existent invoice; expect "invoice not found" error.
        Step 1: Attempt to retrieve an invoice with a random payment hash.
        Step 2: Verify that the error message "invoice not found" is returned.
        """
        # Step 1: Attempt to retrieve an invoice with a random payment hash
        with pytest.raises(Exception) as exc_info:
            self.fiber1.get_client().get_invoice(
                {"payment_hash": self.generate_random_preimage()}
            )

        # Step 2: Verify that the error message "invoice not found" is returned
        expected_error_message = "invoice not found"
        assert expected_error_message in exc_info.value.args[0], (
            f"Expected substring '{expected_error_message}' "
            f"not found in actual string '{exc_info.value.args[0]}'"
        )
